- cluster_regional.tf
- cluster_zonal.tf
- networks.tf
Use data resource rather than path formatting
> Better way to access networks

- cluster_regional.tf
- cluster_zonal.tf
As per the suggestion in Issue #36 -- added support for preemptible nodes in the node config map.
> Added support for preemptible nodes #36

- README.md
This should make #34 easier to avoid.
Fixes #34.
> Add documentation regarding requirements

- examples/simple_zonal/main.tf
- test/integration/simple_zonal/controls/gcloud.rb
Please disregard CI checks, as this is extracted from the changes necessary to get Concourse CI working.
> Update simple-zonal example GKE version

- .github/CODEOWNERS
Once this is merged, I'll enable required reviews on the repository.
> Add `CODEOWNERS` file to codify pull request ownership

- .gitignore
- CHANGELOG.md
- README.md
- cluster_regional.tf
- cluster_zonal.tf
- examples/node_pool/data/shutdown-script.sh
- examples/node_pool/main.tf
- test/integration/node_pool/controls/gcloud.rb
- variables.tf
Expands on https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/47 with test coverage.
> Node pool metadata key value pairs

- modules/private-cluster/README.md
> Add note about Terraform VPC for private clusters.

- Makefile
- autogen/README.md
- modules/private-cluster/cluster_regional.tf
- modules/private-cluster/cluster_zonal.tf
- test/make.sh
This function adds a make target to test if code autogeneration has been run properly. This new target will be added as part of the CI runs to ensure that code is always properly synced from the templates.
> Add function to check code autogeneration

- CHANGELOG.md
This branch updates the Changelog for v1.0.1.
> [ci skip] v1.0.1

- README.md
> Add jq to README; fixes #150

- CHANGELOG.md
- README.md
- autogen/README.md
- examples/deploy_service/main.tf
- examples/disable_client_cert/main.tf
- examples/node_pool/main.tf
- examples/shared_vpc/main.tf
- examples/simple_regional/main.tf
- examples/simple_regional_private/main.tf
- examples/simple_zonal/main.tf
- examples/simple_zonal_private/main.tf
- examples/stub_domains/main.tf
- modules/private-cluster/README.md
> Add support for v2.6, v2.7 of Google providers

- examples/deploy_service/README.md
- examples/deploy_service/outputs.tf
- examples/disable_client_cert/README.md
- examples/disable_client_cert/outputs.tf
- examples/node_pool/README.md
- examples/node_pool/outputs.tf
- examples/shared_vpc/README.md
- examples/shared_vpc/outputs.tf
- examples/simple_regional/README.md
- examples/simple_regional/outputs.tf
- examples/simple_regional_beta/outputs.tf
- examples/simple_regional_private/README.md
- examples/simple_regional_private/outputs.tf
- examples/simple_regional_private_beta/outputs.tf
- examples/simple_zonal/README.md
- examples/simple_zonal/outputs.tf
- examples/simple_zonal_private/README.md
- examples/simple_zonal_private/outputs.tf
- examples/stub_domains/README.md
- examples/stub_domains/outputs.tf
- examples/stub_domains_private/README.md
- examples/stub_domains_private/outputs.tf
- examples/stub_domains_upstream_nameservers/outputs.tf
- examples/upstream_nameservers/outputs.tf
- examples/workload_metadata_config/outputs.tf
- Change description for service account output to sound more like an output
> Fix description for service account output

- CHANGELOG.md
- README.md
- autogen/README.md
- autogen/cluster.tf.tmpl
- cluster.tf
- examples/node_pool/main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
> Add support for local_ssd_count in node config

- CHANGELOG.md
- README.md
- autogen/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
Update the CHANGELOG and README for 6.0.0. Are there any other pull requests we want to hold on before releasing?
> 6.0.0 notes

- autogen/versions.tf.tmpl
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/versions.tf
- versions.tf
> Relax provider version constraint

- autogen/cluster.tf.tmpl
- autogen/main.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/cluster.tf
- modules/private-cluster/main.tf
Fixes #364
Also switched to using a dynamic block for private_cluster_config.
> Fix endpoint output for private clusters

- autogen/main.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
Workaround for #294
But the real issue's with terraform not able to override a default value when importing resources is there.
> Make setting 'region' more clear.

- autogen/outputs.tf.tmpl
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster/outputs.tf
To address 
> Warning: Quoted references are deprecated
> fix: remove quotes from references

- modules/safer-cluster/README.md
- modules/safer-cluster/variables.tf
> Removed quoted type constraints for tf 0.12.14+ support

- autogen/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
> Documented guide about GKE clusters isolation from internet access

- modules/services/main.tf
- modules/services/outputs.tf
- modules/services/variables.tf
This is a simple submodule which can be used to activate all required services.
> Add a service activation module

- auth.tf
- autogen/main/auth.tf.tmpl
- modules/beta-private-cluster-update-variant/auth.tf
- modules/beta-private-cluster/auth.tf
- modules/beta-public-cluster/auth.tf
- modules/private-cluster-update-variant/auth.tf
- modules/private-cluster/auth.tf
Fixes #429 by pinning the provider to 1.10 until issue is fixed upstream.
@qlikcoe FYI
> fix: Pin Kubernetes provider to 1.10

- autogen/main/main.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
Fixes instances of 'Kubernetes' misspelled as 'kuberentes'.
> Fix spelling of Kubernetes

- examples/deploy_service/main.tf
> Simplify value of kubernetes provider host param (issue #461)

- README.md
- autogen/main/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
Properly implements changes from https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/465
> Only include node_pools_taints in example in modules that support it

- docs/upgrading_to_v8.0.md
> upgrade guide 8.0

- .github/CODEOWNERS
Remove @adrienthebo and @aaron-lane.
Add @bharathkkb
> Clean up old CODEOWNERS

- examples/simple_zonal_private/README.md
> Doc fix for zonal cluster

- README.md
- autogen/main/README.md
- examples/stub_domains/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
Add secure boot and integrity monitoring in beta-private-cluster-update-variant README.md
Resolve: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/501
> Add secure boot and integrity monitoring documentation

- autogen_modules.json
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/auth.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/dns.tf
- modules/beta-public-cluster-update-variant/firewall.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/masq.tf
- modules/beta-public-cluster-update-variant/networks.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster-update-variant/sa.tf
- modules/beta-public-cluster-update-variant/scripts/delete-default-resource.sh
- modules/beta-public-cluster-update-variant/scripts/kubectl_wrapper.sh
- modules/beta-public-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster-update-variant/variables_defaults.tf
- modules/beta-public-cluster-update-variant/versions.tf
Closes #543 .
I copied `modules/beta-private-cluster-update-variant` to `modules-beta-public-cluster-update-variant` and ran `make build` to update the necessary files. 
Let me know if there's something missing!
Signed-off-by: Ramon Rüttimann <ramon@nine.ch>
> Add Beta Public Module Update Variant

- .kitchen.yml
- build/int.cloudbuild.yaml
- examples/safer_cluster_iap_bastion/README.md
- examples/safer_cluster_iap_bastion/apis.tf
- examples/safer_cluster_iap_bastion/bastion.tf
- examples/safer_cluster_iap_bastion/cluster.tf
- examples/safer_cluster_iap_bastion/network.tf
- examples/safer_cluster_iap_bastion/outputs.tf
- examples/safer_cluster_iap_bastion/provider.tf
- examples/safer_cluster_iap_bastion/variables.tf
- test/fixtures/safer_cluster_iap_bastion/example.tf
- test/fixtures/safer_cluster_iap_bastion/outputs.tf
- test/fixtures/safer_cluster_iap_bastion/variables.tf
- test/integration/safer_cluster_iap_bastion/controls/e2e.rb
- test/integration/safer_cluster_iap_bastion/inspec.yml
- test/integration/sandbox_enabled/controls/gcloud.rb
- test/setup/iam.tf
Demonstrates a realistic private IP access pattern for a private safer cluster.
Replaces #322
> Add Safer Cluster with IAP bastion host access pattern

- autogen/main/outputs.tf.tmpl
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster/outputs.tf
- modules/private-cluster-update-variant/outputs.tf
- modules/private-cluster/outputs.tf
- outputs.tf
fixes #567 using `module.gcloud_wait_for_cluster.wait`
> fix: Restore gcloud wait_for_cluster

- modules/asm/scripts/install_asm.sh
> New asm release 1.6 with gcloud 299.0.0

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- examples/simple_regional_beta/README.md
- examples/simple_regional_beta/main.tf
- examples/simple_regional_beta/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
- test/fixtures/beta_cluster/main.tf
> Replace PodSecurityPolicy implementation

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/node_pool/main.tf
- examples/node_pool_update_variant/main.tf
- examples/node_pool_update_variant_beta/main.tf
- examples/safer_cluster_iap_bastion/cluster.tf
- examples/simple_regional_private/main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- test/integration/beta_cluster/controls/gcloud.rb
- test/integration/node_pool/controls/gcloud.rb
- test/integration/safer_cluster/controls/gcloud.rb
- test/integration/simple_regional/controls/gcloud.rb
- test/integration/simple_regional_private/controls/gcloud.rb
- test/integration/simple_regional_with_kubeconfig/controls/gcloud.rb
- test/integration/simple_regional_with_networking/controls/gcloud.rb
- test/integration/simple_zonal/controls/gcloud.rb
- test/integration/simple_zonal_private/controls/gcloud.rb
e2-medium VMs are more efficient and the default going forward.
> feat!: Changed default node pool machine type to e2-medium

- docs/upgrading_to_v11.0.md
Adds upgrade guide for 11.0 release
> 11.0 upgrade guide

- modules/k8s-operator-crd-support/main.tf
> fix: CRD concurrent runs should use unique manifest paths

- README.md
> readme: change link to examples to folder to be absolute

- modules/k8s-operator-crd-support/main.tf
> fix: add created configmanagement yaml content to triggers 

- autogen/main/cluster.tf.tmpl
- autogen/main/dns.tf.tmpl
- cluster.tf
- dns.tf
- modules/asm/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/dns.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/dns.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/dns.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/dns.tf
- modules/hub/main.tf
- modules/k8s-operator-crd-support/main.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/dns.tf
- modules/private-cluster/cluster.tf
- modules/private-cluster/dns.tf
- modules/workload-identity/main.tf
fixes #630 
todo: test https://github.com/terraform-google-modules/terraform-google-gcloud/pull/76
> fix: Upgrade gcloud module to latest version

- modules/acm/README.md
- modules/acm/main.tf
- modules/acm/variables.tf
- modules/k8s-operator-crd-support/main.tf
- modules/k8s-operator-crd-support/variables.tf
Not déjà vu :) Same change as ASM but this time for ACM.
> Expose service account variable for ACM module

- modules/workload-identity/README.md
> fix: incorrect WI source in docs

- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- test/bundle.hcl
- test/integration/beta_cluster/controls/gcp.rb
- test/integration/beta_cluster/inspec.yml
- test/integration/private_zonal_with_networking/controls/gcloud.rb
- test/integration/private_zonal_with_networking/inspec.yml
- test/integration/safer_cluster/inspec.yml
- test/integration/simple_regional_with_networking/inspec.yml
- test/integration/simple_zonal/controls/gcp.rb
- test/integration/simple_zonal/inspec.yml
ref: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/773
TODO:
> feat: Provider cache for lint

- autogen/main/cluster.tf.tmpl
- autogen/main/firewall.tf.tmpl
- autogen/main/outputs.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/firewall.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/firewall.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/firewall.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/firewall.tf
- modules/beta-public-cluster/outputs.tf
- modules/beta-public-cluster/variables.tf
This PR adds support for TPUs in beta modules.
> Feat: Add TPU support

- modules/auth/README.md
This PR adds documentation for Inputs and Outputs for `auth` submodule.
> Add documentation for Inputs and Outputs for auth submodule

- autogen/main/cluster.tf.tmpl
- autogen/main/main.tf.tmpl
- cluster.tf
- main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/cluster.tf
- modules/private-cluster/main.tf
autoscalling -> autoscaling
Effectively a complete version of #751.
> Fix typo in local variable

- examples/acm-terraform-blog-part1/README.md
- examples/acm-terraform-blog-part1/config-root/wordpress-bundle.yaml
- examples/acm-terraform-blog-part2/config-root/wordpress-bundle.yaml
small tweak, want to noise from `default` namespace violations in the audit chapter.
> moved example out of default ns, will help audit later

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
> fix: ignore ASM labels

- test/fixtures/node_pool/example.tf
- test/fixtures/node_pool/network.tf
- test/integration/node_pool/controls/gcloud.rb
tests seem to be failing due to a quota issue for GPUs
> chore: switch region for gpu quota

- modules/workload-identity/README.md
- modules/workload-identity/variables.tf
Update the documentation of the workload identity module to address issue #1065
> Update README to prevent KSA misconfiguration

- modules/asm/scripts/create_cpr.sh
To be used for install attribution
> Add app.kubernetes.io/created-by label to CPR in ASM module

- modules/asm/README.md
- modules/asm/versions.tf
[modules/asm/variables.tf](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/asm/variables.tf) makes use of TF function [anytrue](https://www.terraform.io/language/functions/anytrue) which requires TF v0.14+ Closes #1206
> fix: ASM module requires TF 0.14+

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
> fix: convert gcfs_config to dynamic block

- modules/acm/README.md
> chore: update ACM docs

- test/fixtures/safer_cluster_iap_bastion/example.tf
Fixes https://github.com/terraform-google-modules/terraform-google-gcloud/issues/119
> chore: suppress IAP numPy warnings for CI

- examples/acm-terraform-blog-part1/terraform/gke.tf
- examples/acm-terraform-blog-part2/terraform/gke.tf
- examples/acm-terraform-blog-part3/terraform/gke.tf
- examples/acm-terraform-blog-part3/terraform/providers.tf
Updated version to 21.2 from 16.0 which has fixed the issue.
> Update version to fix the exception of node pool to terraform

- README.md
- autogen/main/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
Example node_pools_oauth_scopes in usage with reasonable default
Fixes #1361
> chore: example node_pools_oauth_scopes usage

- modules/acm/feature.tf
> feat: enable PoCo referential_rules for ACM

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/main/versions.tf.tmpl
- cluster.tf
- docs/upgrading_to_v24.0.md
- examples/simple_regional/main.tf
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
move the config outside the logic of beta only
> feat!: cost_management_config is out of beta now

- build/int.cloudbuild.yaml
> chore: re enable hub tests

- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/variables.tf
- variables.tf
- Update description to match the validation rule
Fixes: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1438
> fix: Update variable validation description

- test/integration/private_zonal_with_networking/testdata/TestPrivateZonalWithNetworking.json
> chore: add windowsNodeConfig for CI

- examples/simple_zonal_with_acm/acm.tf
- modules/acm/README.md
As advised by the notice at the top of https://github.com/GoogleCloudPlatform/csp-config-management
> chore: sync repo acm location update

- modules/auth/versions.tf
- test/fixtures/safer_cluster_iap_bastion/version.tf
> fix: auth module avoid TPG v4.49.0

- modules/auth/versions.tf
- test/fixtures/safer_cluster_iap_bastion/version.tf
> fix: auth module avoid TPG v4.50.0

- autogen/main/main.tf.tmpl
- examples/simple_zonal_with_acm/acm.tf
- main.tf
- modules/beta-autopilot-private-cluster/main.tf
- modules/beta-autopilot-public-cluster/main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
- test/integration/beta_cluster/testdata/TestBetaCluster.json
- test/integration/sandbox_enabled/testdata/TestSandboxEnabled.json
- test/integration/simple_autopilot_private_non_default_sa/simple_autopilot_private_non_default_sa_test.go
- test/integration/simple_windows_node_pool/testdata/TestSimpleWindowsNodePool.json
Solves https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1442
> fix: random zones only when zones are not provided

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- Updated guest_accelerator to add gpu driver installation
> feat: add support for gpu_driver_installation_config on nodepool

- autogen/main/sa.tf.tmpl
- docs/upgrading_to_v29.0.md
- docs/upgrading_to_v30.0.md
- modules/beta-autopilot-private-cluster/sa.tf
- modules/beta-autopilot-public-cluster/sa.tf
- modules/beta-private-cluster-update-variant/sa.tf
- modules/beta-private-cluster/sa.tf
- modules/beta-public-cluster-update-variant/sa.tf
- modules/beta-public-cluster/sa.tf
- modules/private-cluster-update-variant/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
This reverts commit 350faa747659202de58bef64de67c94845b223ff.
> fix!: Revert create least privilege default service account (#1757)

- test/integration/testutils/retry.go
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1794#issuecomment-1894651185
> chore(CI): retry on quota exceeded

- examples/simple_zonal_with_asm/main.tf
> chore(CI): bump machine type

- test/integration/deploy_service/deploy_service_test.go
- test/integration/simple_zonal/simple_zonal_test.go
- test/integration/simple_zonal_with_asm/simple_zonal_with_asm_test.go
- test/integration/testutils/json.go
> chore(CI): filter kubectl error msgs

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
allow more than 1 nvme ssd disk to be attached to a given compute engine
> fix: local nvme ssd count

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
supersedes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1900
> feat: add notification event filter

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
fix copy paste mistake from https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2003
> fix: enable_confidential_storage fix

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
> feat: add optional private_endpoint_subnetwork variable in private submodules

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- examples/autopilot_private_firewalls/main.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
> feat: enable binauthz for autopilot

- autogen/main/cluster.tf.tmpl
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
> fix: remove duplicte enable_secure_boot

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- docs/upgrading_to_v33.0.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
- replace deprecated `relay_mode` with `enable_relay`
> fix!: update relay_mode to enable_relay

- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- test/integration/node_pool/controls/gcloud.rb
Fixes: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/2075
Workaround: https://github.com/hashicorp/terraform-provider-google/issues/19428
TODO: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/2079
> fix: avoid TPGv5.44.0 with Autopilot

- modules/acm/feature.tf
- modules/acm/versions.tf
- Add `config_sync.enabled` introduced in TPG v5.41
> fix(TPG>=5.41)!: add config_sync.enabled

- modules/asm/versions.tf
- modules/auth/versions.tf
> fix: asm and auth allow TPGv6

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
> fix: no gcfs block when enable_gcfs  null

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
feat: enable L4 ILB subsetting support for safer clusters
> feat: enable L4 ILB subsetting support for safer clusters

- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- Confirmed issues resolved in 5.44.1 and 6.4.0
> fix(autopilot): narrow version exclusion

- test/integration/private_zonal_with_networking/testdata/TestPrivateZonalWithNetworking.json
Reverts terraform-google-modules/terraform-google-kubernetes-engine#2134
> Revert "chore(CI): update testdata with insecureKubeletReadonlyPortEnabled"

- test/integration/beta_cluster/beta_cluster_test.go
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6982
> chore(CI): add beta_cluster_test DefaultVerify

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
Matches the other submodules inputs
> feat: add logging_config and monitoring_config to autopilot modules

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
> feat: Node pools can enable fast_socket

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
> fix: node pool creation should depend on necessary firewall rules

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/integration/private_zonal_with_networking/private_zonal_with_networking_test.go
- test/integration/simple_regional_private/simple_regional_private_test.go
- test/integration/simple_zonal_private/simple_zonal_private_test.go
> fix: network_config with just enable_private_nodes

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/node_pool/main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
> feat: add node_affinity

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
> feat: add enterprise config

- examples/simple_autopilot_private/main.tf
- examples/simple_autopilot_private_cmek/main.tf
- examples/simple_autopilot_private_non_default_sa/main.tf
- examples/simple_autopilot_public/main.tf
> chore(CI): temporarily disable AP cgroup test

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
allow for node pools with nodes with max lifetime before they are recycled
> feat: add support for max_run_duration

- examples/gke_autopilot_cluster/main.tf
- examples/gke_standard_cluster/main.tf
- modules/gke-autopilot-cluster/metadata.yaml
- modules/gke-node-pool/metadata.yaml
- modules/gke-standard-cluster/metadata.yaml
- test/setup/iam.tf
- test/setup/main.tf
This PR update the list of roles and services required by the ADC modules
> fix(metadata): update ADC roles and services per module
