terraform-google-modules/terraform-google-kubernetes-engine

- cluster_regional.tf
- cluster_zonal.tf
- main.tf
- outputs.tf
- variables.tf
Many GKE users opt to use different logging and monitoring
apis (e.g. DataDog) and would like to have the option to
disable StackDriver monitoring and logging.
> Add options to specify monitoring and logging services

- cluster_regional.tf
- cluster_zonal.tf
- outputs.tf
- variables.tf
> Enable specifying  master_authorized_networks_config

- test/integration/gcloud/run.sh
On my machine, with a clean checkout, I encountered two problems trying to run the test suite:
* `run.sh` tries to run `kitchen` commands without entering the `bundle` context, potentially causing errors loading the `kitchen-terraform` gem
* While the provider is available when Terraform code is generated for integration tests, it is not explicitly set in the `google` provider, causing errors when it is not otherwise configured.
> Get tests running

- networks.tf
My environment is on GKE with shared VPC network.
And, I've got an error below when I tried 'terraform plan'. I believe this PR fix my issue.
```
data.google_compute_subnetwork.gke_subnetwork: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```
Terraform Code:
```
module "gke-cluster-my-cluster" {
source              = "github.com/terraform-google-modules/terraform-google-kubernetes-engine"
project_id          = "my_project"
name                = "my_cluster"
kubernetes_version  = "1.10.6-gke.2"
regional            = false
region              = "us-east4"
zones               = ["us-east4-a"]
network_project_id  = "my_network_project"
network             = "my_network"
subnetwork          = "my_subnet"
ip_range_pods       = "my_cidr_container" …
```
> `region` is required for `google_compute_subnetwork`

- variables.tf
Removes explicit patch suffix to allow usage of latest when launching new clusters. Only the latest tends to be supported.
Closes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/24.
> Default K8s Version Uses Latest Patch Suffix for 1.10.6

- variables.tf
This is as opposed to letting GKE figure out the latest patch suffix. This strategy does not work for specifying node version - only masters. An explicit patch suffix is required for node version.
Latest, "...specifies the highest supported Kubernetes version currently available on GKE in the cluster's zone or region" [1]. I've tested this in `us-west1`, `us-west2`, and `us-central1` and it's worked as suspected - all masters and nodes were launched with version 1.11.2-gke.18.
An alternate approach would be to use the [`google_container_engine_versions` data source](https://www.terraform.io/docs/providers/google/d/google_container_engine_versions.html). This would be useful if we had a need to target a specific minor or patch version as the default. I would argue that it's more …
> Master and Node Versions Default to Latest

- CHANGELOG.md
- README.md
- variables.tf
I just wanted to do a step further with #42 issue reported recently. It might be considered a cosmetic change, but I deeply believe following the standards from the `google_container_cluster` resource is more than appropriate. 
The choose of `false` comes from 21ec8db89dcf0c27fe80ccf2b28703500e234768 which is the very first commit from this module, hence this might be worth updating.
Fixes #42.
> Set horizontal_pod_autoscaling to true by default

- test/integration/simple_regional/controls/gcloud.rb
- test/integration/simple_zonal/controls/gcloud.rb
- test/integration/stub_domains/controls/gcloud.rb
This was compounded by an erroneous Concourse pipeline config, where an error in running the integration tests would cause the created resources to be cleaned up, but would not actually trigger a failure. This has since been corrected.
> Fix failing horizontal-pod-autoscaling tests

- cluster_regional.tf
- cluster_zonal.tf
- examples/deploy_service/main.tf
- examples/deploy_service/variables.tf
- examples/node_pool/main.tf
- examples/node_pool/variables.tf
- examples/shared_vpc/main.tf
- examples/shared_vpc/variables.tf
- examples/simple_regional/main.tf
- examples/simple_regional/variables.tf
- examples/simple_zonal/main.tf
- examples/simple_zonal/variables.tf
- examples/stub_domains/main.tf
- examples/stub_domains/variables.tf
- test/fixtures/deploy_service/example.tf
- test/fixtures/node_pool/example.tf
- test/fixtures/shared_vpc/example.tf
- test/fixtures/simple_regional/example.tf
- test/fixtures/simple_zonal/example.tf
- test/fixtures/stub_domains/example.tf
- test/integration/node_pool/controls/gcloud.rb
Reduces likelihood of naming collisions when running tests in parallel.
> Add random suffix to end of cluster names during testing

- README.md
- cluster_regional.tf
- cluster_zonal.tf
- variables.tf
In the #15 issue there was a request for remove_default_node_pool. I'm interested in introducing this to the module. There's no point in keeping the default node pool the `google_container_cluster` forces us to have on the beginning. Usually, the one wants to manage the pools explicitly, and so do I, hence this PR.
Adding the `remove_default_node_pool` was not enough to make it work perfectly. A change in the manner of providing the `google_container_cluster` with the network and subnetwork parameters had to be changed as well. Without it, terraform produced permadiff with every `plan` and `apply`.  That's the issue with google provider, more on that is described [in this google provider issue](https://github.com/terraform-providers/terraform-provider-google/issues/1566). 
The approach I …
> Add remove_default_node_pool

- CHANGELOG.md
We forgot to add this quite significant feature into CHANGELOG.
> Add missing remove_default_node_pool to CHANGELOG

- .kitchen.yml
Disable flashing red output in Concourse, replacing with plaintext output.
> Disable color output when running tests

- examples/deploy_service/main.tf
- examples/node_pool/main.tf
- examples/shared_vpc/main.tf
- examples/simple_regional/main.tf
- examples/stub_domains/main.tf
- test/integration/deploy_service/controls/gcloud.rb
- test/integration/simple_regional/controls/gcloud.rb
At one point, these were necessary to ensure that tests passed, particularly when working with zonal clusters. This does not seem to be the case any longer, and merely add overhead, as they have to be updated to keep tests green.
> Remove explicit versions from test cases and examples

- CHANGELOG.md
- README.md
- cluster_regional.tf
- cluster_zonal.tf
Hi,
I wanted to extend the node_pool block parameters a bit and add optional, explicitly set initial_node_count for node pool. It assumes the min_count or 1 when not defined, so it doesn't affect anyone when not set. 
We need this to start new node pool with predefined node count even when autoscaling minimal value is set lower, useful especially when adding new node pool as a reaction to increased traffic etc.
I added no tests. If there's anyone willing to write them since I haven't had a chance yet, please don't hesitate.
> Add initial_node_count var for node_pool block

- README.md
Add updates missing from the [integration tests](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine#integration-test) section of README.md after Concourse changes.
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/67
> Add missing updates to README

- README.md
Addresses https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/68
> Add explicit note about running `kitchen converge` twice

- examples/simple_zonal/main.tf
- test/integration/simple_zonal/controls/gcloud.rb
The explicit version in the simple_zonal example is causing failures as
1.11.4-gke.13 has been dropped as a valid master version. This commit
drops the explicit versions in the simple_zonal example; we can just use
the latest version avilable.
> Drop explicit version from simple_zonal example

- examples/deploy_service/main.tf
- examples/node_pool/main.tf
- examples/shared_vpc/main.tf
- examples/simple_regional_private/main.tf
- examples/simple_zonal/main.tf
- examples/simple_zonal_private/main.tf
- examples/stub_domains/main.tf
The google and google-beta providers are causing some issues with the simple-regional-private example; these issues in turn are causing CI to fail for all recent pull requests. This commit repairs CI by pinning the version of the google and google-beta providers; we can address v2.0 support in the future.
> Lock google, google-beta provider version to ~> 1.20      

- examples/deploy_service/main.tf
Changes in GKE 1.12 have caused node pool resources to become unstable;
in turn this has caused the deploy-service example and tests to become
unreliable.
This commit bypasses the problem by pinning the GKE version to 1.11 to
get CI passing again. Once CI is green we can resolve the root cause
while other pull requests are reviewed.
> examples/deploy-service: pin GKE version to 1.11

- cluster_zonal.tf
The regional and zonal node pool configurations had different defaults for `auto_upgrade`. We prefer auto-upgrading node pools in general, and moreover having different defaults for regional and zonal node pools is very surprising.
This commit reconciles the difference by changing the zonal node pool auto_upgrade default to true.
> Synchronize zonal and regional node pool auto_upgrade default

- examples/node_pool/main.tf
- examples/node_pool/variables.tf
- test/fixtures/node_pool/example.tf
When GKE stands up a cluster with more than 6 nodes in the node pool, it will automatically resize the master node. This causes the cluster to enter reconciling, which fouls up our CI configuration.
This commit sidesteps this problem by converting the node-pool example to a zonal pool, removing the default node pool and shrinking the max size of the added node pools. We can add graceful handling of cluster reconciliation in a followup PR.
This pull request depends on #98.
> Ensure node-pool example node count < 6

- autogen/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
Fixes the following error:
```
* module.gke.google_service_account.cluster_service_account: substr: 'offset + length' cannot be larger than the length of the string in:
tf-gke-${substr(var.name, 0, 20)}
```
> Fix issues with `substr` for Service Accounts

- autogen/outputs.tf
- autogen/sa.tf
- examples/deploy_service/outputs.tf
- examples/node_pool/outputs.tf
- examples/shared_vpc/outputs.tf
- examples/simple_regional/outputs.tf
- examples/simple_regional_private/outputs.tf
- examples/simple_zonal/outputs.tf
- examples/simple_zonal_private/outputs.tf
- examples/stub_domains/outputs.tf
- modules/private-cluster/outputs.tf
- modules/private-cluster/sa.tf
- outputs.tf
- sa.tf
- test/fixtures/shared/outputs.tf
- test/integration/simple_zonal/controls/gcloud.rb
- test/integration/simple_zonal/inspec.yml
The service account ID truncation may drop appended to the cluster name; this means that multiple clusters with a common prefix but different name may try to create service accounts with identical IDs and then fail.
This commit resolves the issue by adding a suffix to the service account name to ensure uniqueness.
> Add suffix to cluster service account

- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/variables.tf
- cluster_regional.tf
- cluster_zonal.tf
- examples/node_pool/main.tf
- modules/private-cluster/cluster_regional.tf
- modules/private-cluster/cluster_zonal.tf
- modules/private-cluster/variables.tf
- test/integration/node_pool/controls/gcloud.rb
- variables.tf
GKE 1.12 and later defaults to disabling legacy endpoints; this default
behavior injects additional metadata into the node pool metadata. The
addition of this metadata causes node pools to be destroyed and rebuilt
every time Terraform runs.
> Fix permanent metadata skew due to disable-legacy-endpoints keys

- README.md
- autogen/README.md
- examples/deploy_service/README.md
- examples/node_pool/README.md
- examples/shared_vpc/README.md
- examples/simple_regional/README.md
- examples/simple_regional_private/README.md
- examples/simple_zonal/README.md
- examples/simple_zonal_private/README.md
- examples/stub_domains/README.md
- modules/private-cluster/README.md
- test/make.sh
The generate_docs function would attempt to run terraform_docs against
the autogen/ directory. Since that directory contains templates instead
of actual working Terraform, the terraform-docs command failed, causing
no docs to be properly formatted.
These changes update the function to properly ignore the ./autogen
directory.
Also, updates the documentation.
> [skip ci] Fix documentation generation and update docs

- Makefile
- test/make.sh
As it stands, it has become very easy for documentation to become out of date due to forgetting to run generate or generate_docs before submitting a PR. This PR adds a make target to verify that documentation has been properly generated for use in CI.
> Add check for generating docs

- README.md
- autogen/README.md
- examples/deploy_service/main.tf
- examples/disable_client_cert/main.tf
- examples/node_pool/main.tf
- examples/shared_vpc/main.tf
- examples/simple_regional/main.tf
- examples/simple_regional_private/main.tf
- examples/simple_zonal/main.tf
- examples/simple_zonal_private/main.tf
- examples/stub_domains/main.tf
- modules/private-cluster/README.md
Intended to address issues with providers `>= 2.4.0`
> Version-pin all Google providers in examples to ~> 2.3.0

- .kitchen.yml
- CHANGELOG.md
- autogen/main.tf
- autogen/variables.tf
- examples/stub_domains_private/README.md
- examples/stub_domains_private/main.tf
- examples/stub_domains_private/outputs.tf
- examples/stub_domains_private/test_outputs.tf
- examples/stub_domains_private/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/main.tf
- modules/private-cluster/variables.tf
- test/fixtures/stub_domains_private/main.tf
- test/fixtures/stub_domains_private/outputs.tf
- test/fixtures/stub_domains_private/variables.tf
- test/integration/stub_domains_private/controls/gcloud.rb
- test/integration/stub_domains_private/controls/kubectl.rb
- test/integration/stub_domains_private/inspec.yml
This branch adds the ability to deploy a cluster using the private endpoint from within the cluster subnet while still exposing the public endpoint.
> Add deploy_using_private_endpoint variable

- README.md
- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/variables.tf
- cluster_regional.tf
- cluster_zonal.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster_regional.tf
- modules/private-cluster/cluster_zonal.tf
- modules/private-cluster/variables.tf
- variables.tf
Adds a variable to be able to configure the number of nodes in the default node pool. It defaults to 0 so it should not change existing behaviour.
> Add initial_node_count variable for scaling the default node pool

- .kitchen.yml
- README.md
- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/variables.tf
- cluster_regional.tf
- cluster_zonal.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster_regional.tf
- modules/private-cluster/cluster_zonal.tf
- modules/private-cluster/variables.tf
- test/ci_integration.sh
- variables.tf
This branch adds an explicit `network_policy` block to the `google_container_cluster`, as recommended by https://github.com/terraform-providers/terraform-provider-google/issues/3673. This solves the issue of the partially converged suites which obviates the need for a second converge.
> Add network_policy to google_container_cluster

- Makefile
Avoids issues with non-standard directory names, e.g. those with spaces or special characters in them
> Quote current directory in Makefile

- .dockerignore
- Makefile
Significantly reduces the time needed to build the testing Docker image.
Before:
```
❯ make docker_build_kitchen_terraform
docker build -f build/docker/kitchen_terraform/Dockerfile \
--build-arg BASE_IMAGE=gcr.io/cloud-foundation-cicd/cft/kitchen-terraform:1.3.0 \
-t gcr.io/cloud-foundation-cicd/cft/kitchen-terraform_terraform-google-kubernetes-engine:1.3.0 .
Sending build context to Docker daemon  2.866GB
Step 1/9 : ARG BASE_IMAGE
Step 2/9 : FROM $BASE_IMAGE
---> 37b95e37e5c1
Step 3/9 : RUN apk add --no-cache     ca-certificates=20190108-r0
---> Using cache
---> 02e795605df7
Step 4/9 : ADD https://storage.googleapis.com/kubernetes-release/release/v1.12.2/bin/linux/amd64/kubectl /usr/local/bin/kubectl
Downloading [==================================================>]  57.35MB/57.35MB
---> …
```
> Add Terraform and Kitchen state files to Dockerignore

- test/make.sh
This changes "pip" to "pip3" in make.sh.
On systems that have both python2 and python3 installed, we may want to use
a call to pip3 for installing modules, rather than just pip.
On my mac, it was not happy as I have both pip and pip3 installed.
> Change to use pip3

- README.md
- autogen/masq.tf
- autogen/variables.tf
- examples/stub_domains/main.tf
- masq.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/masq.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/masq.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/masq.tf
- modules/private-cluster/variables.tf
- test/integration/stub_domains_private/controls/kubectl.rb
- variables.tf
Aliased IP addresses do not require ip masquerading anymore.  There are  few use cases where we would need ip masq, but usually it is not recommended to install ip masquerading. This variable allows
for fine gain control on the installation of ip masq as it was always installed via the
network_policy variable previously.
configure_ip_masq defaults to false.
Fixes: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/172
TODO:
Added a new field 'configure_ip_masq' to public stub domain example.  Removed the
integration control to check for ip masq in the private cluster as well.
> Creation of new variable configure_ip_masq controlling ip masq install

- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/main.tf
- autogen/outputs.tf
- autogen/variables.tf
- cluster_zonal.tf
- modules/beta-private-cluster/cluster_zonal.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster_regional.tf
- modules/beta-public-cluster/cluster_zonal.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/outputs.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster_regional.tf
- modules/private-cluster/cluster_zonal.tf
- modules/private-cluster/main.tf
- modules/private-cluster/outputs.tf
- modules/private-cluster/variables.tf
This allows pod security policies and binary authorization to be used
by both beta private and  beta public clusters. Previously these two features
where limited to only private clusters, and this commit also removes
that functionality from private clusters.
> Enabling two features in beta clusters

- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/main.tf
- cluster_regional.tf
- cluster_zonal.tf
- main.tf
- modules/beta-private-cluster/cluster_regional.tf
- modules/beta-private-cluster/cluster_zonal.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/cluster_regional.tf
- modules/beta-public-cluster/cluster_zonal.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster/cluster_regional.tf
- modules/private-cluster/cluster_zonal.tf
- modules/private-cluster/main.tf
This branch patches the network policy and CloudRun config implementations so that they are backwards compatible and do not force the recreation of a cluster. A consequence of these changes is that the `cloudrun_enabled` output is no longer dependent on the clusters as the `cloudrun_config` argument is  omitted in the disabled case which breaks the existing output logic.
> Patch breaking changes

- .kitchen.yml
- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/main.tf
- autogen/variables.tf
- examples/workload_metadata_config/README.md
- examples/workload_metadata_config/main.tf
- examples/workload_metadata_config/outputs.tf
- examples/workload_metadata_config/test_outputs.tf
- examples/workload_metadata_config/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster_regional.tf
- modules/beta-private-cluster/cluster_zonal.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster_regional.tf
- modules/beta-public-cluster/cluster_zonal.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
- test/ci/workload-metadata-config.yml
- test/fixtures/workload_metadata_config/example.tf
- test/fixtures/workload_metadata_config/network.tf
- test/fixtures/workload_metadata_config/outputs.tf
- test/fixtures/workload_metadata_config/terraform.tfvars
- test/fixtures/workload_metadata_config/variables.tf
- test/integration/workload_metadata_config/controls/gcloud.rb
- test/integration/workload_metadata_config/inspec.yml
This PR is implementation of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/166 based on @aaron-lane's last comment.
See https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/166 for more details.
> Restrict node access to cluster metadata service

- autogen/outputs.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster/outputs.tf
- modules/private-cluster/outputs.tf
- outputs.tf
> Changed the endpoint variable to be dependent on GKE cluster state

- CHANGELOG.md
- autogen/cluster_regional.tf
- autogen/cluster_zonal.tf
- autogen/main.tf
- autogen/outputs.tf
- autogen/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster_regional.tf
- modules/beta-private-cluster/cluster_zonal.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster_regional.tf
- modules/beta-public-cluster/cluster_zonal.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/outputs.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster/outputs.tf
- outputs.tf
Implements some of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/196
Add the simple bool flags for
- vertical_pod_autoscaling
- enable_intranode_visibility
> Add IntraNode Visibility/VerticalPodAutoscaling

- CHANGELOG.md
- autogen/cluster.tf
- autogen/main.tf
- autogen/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
Follow up PR after #216 gets merged, will rebase then.
Related PR: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/196
> Add Authenticator Groups

- CHANGELOG.md
- README.md
- autogen/sa.tf
- autogen/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/sa.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/sa.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/sa.tf
- modules/private-cluster/variables.tf
- sa.tf
- variables.tf
* Added `grant_registry_access` variable to grant `roles/storage.objectViewer` to created SA (Fixes #229)
> Add 'grant_registry_access' variable to add 'storage.objectViewer'-role to SA

- autogen/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
Fixes this error:
```
Error: Invalid index
on .terraform/modules/gke/modules/beta-private-cluster/main.tf line 97, in locals:
97:   cluster_output_pod_security_policy_enabled      = google_container_cluster.primary.pod_security_policy_config.0.enabled
|----------------
| google_container_cluster.primary.pod_security_policy_config is empty list of object
The given key does not identify an element in this collection value.
Error: Invalid index
on .terraform/modules/gke/modules/beta-private-cluster/main.tf line 99, in locals:
99:   cluster_output_vertical_pod_autoscaling_enabled = google_container_cluster.primary.vertical_pod_autoscaling.0.enabled
|----------------
| google_container_cluster.primary.vertical_pod_autoscaling is empty list of object
The given key does not identify an element …
```
> Check null and length of beta feature outputs

- autogen/cluster.tf
- cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster/cluster.tf
Currently, the `var.initial_node_count` is not specified from the variable.
This forces a cluster replacement:
```
- initial_node_count          = 1 -> null # forces replacement
```
An alternative is adding to `ignore_lifecycle`, like what we do with the `node_pool.*.initial_node_count`
> Set cluster initial node count from var

- autogen/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
Some beta feature fields may not be returned by the Google API call that terraform uses.
According to Google Support (Case 20165122), when asked why certain Google API calls don't return `istio_config` or `pod_security_policy_config`: 
```
Actually the fields are not optional. If you have those features enabled in your cluster it will show up in the description. These fields default to disabled and when they are disabled they are not present in the rest resource which is why these fields are missing in the cluster description. The API is configured to register them as disabled if left blank.
```
Since the terraform provider upstream operates by transpiling the API call into the correct resources, I thought it might be most appropriate to code defensively here and check for the field …
> Added check for beta feature field istio_enabled

- CHANGELOG.md
- docs/upgrading_to_v5.0.md
- helpers/migrate.py
> Release v5.0.0

- helpers/migrate.py
This change applies the suggestions from flake8 in the `check_python` function to `helpers/migrate.py` and should resolve https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/277
> apply suggestions from flake8 to helpers/migrate.py

- README.md
- autogen/README.md
- autogen/sa.tf
- autogen/variables.tf
- examples/workload_metadata_config/main.tf
- examples/workload_metadata_config/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/sa.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/sa.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/sa.tf
- modules/private-cluster/variables.tf
- sa.tf
- test/fixtures/shared/outputs.tf
- test/fixtures/shared/variables.tf
- test/fixtures/workload_metadata_config/example.tf
- test/integration/workload_metadata_config/controls/gcloud.rb
- test/integration/workload_metadata_config/inspec.yml
- test/setup/make_source.sh
- variables.tf
The PR allows configuring the project holding the GCR registry when
used in connection with 'create_service_account'=true and
grant_registry_access=true.
Holding the GCR is a project with other resources increases the risk of
exposing sensitive data to the service account running the nodes, as the
required permissions of role roles/storage.objectViewer provide access
to all storage objects in the project.
> Add a parameter 'registry_project_id' to the GKE module templates

- autogen/cluster.tf
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
**SUMMARY**
A number of default tags, metadata and labels are added to the nodepools by the different modules. This is fine when creating a new nodepool, but can be problematic when importing an existing nodepool that does not have those, as a new plan will lead to nodepool recreation, for example:
```
~ labels            = { # forces replacement
+ "cluster_name" = "cluster-somename-9965"
+ "node_pool"    = "basic-pool"
}
```
**PROPOSED CHANGE**
The proposed change makes it possible to use the modules with existing gke clusters/nodepools. It's not introducing any breaking changes and was tested with the beta private cluster. I'm happy to update the other modules, if you think the change makes sense.
> Make default metadata, labels and tags optional in beta private cluster

- .kitchen.yml
- autogen/cluster.tf
- build/int.cloudbuild.yaml
- examples/simple_regional_beta/README.md
- examples/simple_regional_beta/main.tf
- examples/simple_regional_beta/test_outputs.tf
- examples/simple_regional_beta/variables.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
- test/fixtures/sandbox_enabled/example.tf
- test/fixtures/sandbox_enabled/network.tf
- test/fixtures/sandbox_enabled/outputs.tf
- test/fixtures/sandbox_enabled/variables.tf
- test/integration/sandbox_enabled/controls/gcloud.rb
- test/integration/sandbox_enabled/inspec.yml
* Moved `sanbox_config` to `node_pool` resouse (Fix #240)
* Created test for sandbox (Fix #252)
> Add test for sandbox

- CHANGELOG.md
- autogen/cluster.tf
- autogen/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
Expose [enabled_shielded_nodes](https://www.terraform.io/docs/providers/google/r/container_cluster.html#enable_shielded_nodes) which was released as part of the provider 2.18.0 (October 23, 2019) release.
https://cloud.google.com/kubernetes-engine/docs/how-to/shielded-gke-nodes
> Add Shielded Nodes beta field

- autogen/versions.tf
- examples/deploy_service/main.tf
- examples/disable_client_cert/main.tf
- examples/node_pool_update_variant/main.tf
- examples/shared_vpc/main.tf
- examples/simple_regional/main.tf
- examples/simple_regional_private/main.tf
- examples/simple_zonal/main.tf
- examples/simple_zonal_private/main.tf
- examples/stub_domains/main.tf
- examples/stub_domains_private/main.tf
- examples/stub_domains_upstream_nameservers/main.tf
- examples/upstream_nameservers/main.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/versions.tf
- versions.tf
Fixes #261
Bumbed minimal provider version to 2.18
> #261: Invalid plan when re-applying terraform module

- autogen/outputs.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/outputs.tf
When configuring workload identity, there is the possibility that when creating an IAM binding, Terraform attempts to create the binding, before the workload identity is configured by GKE.  This PR creates a tighter dependency between the creation of a GKE cluster and the availability of the workload identity.
This is the first step in addressing https://github.com/forseti-security/terraform-google-forseti/issues/298.
> Tying identity namespace output to successful cluster creation.

- CHANGELOG.md
- autogen/cluster.tf
- cluster.tf
- examples/node_pool/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/fixtures/shared/variables.tf
- test/integration/node_pool/controls/gcloud.rb
- test/integration/node_pool/controls/kubectl.rb
Fixes #311 
When `autoscaling` is `false` for a node pool only `node_count` should be set. `initial_node_count` should be empty. 
Also uses a new node pool var `node_count` rather than using `min_count` to match the provider vars.  #297 should be updated to include this (defaults to `1`). 
A node pool without autoscaling can be created with
```
{
autoscaling = false
node_count = 2 
...
}
```
> Don't set initial_node_count when autoscaling disabled on node pool

- autogen/cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
Fixes #326 by simply setting node_locations to `null` if they're not specified on the individual node pool. This should be closer to the default provider behavior and reduce spurious diffs.
> Don't attempt to set node_locations on pools if unspecified

- .kitchen.yml
- examples/private_zonal_with_networking/main.tf
- examples/private_zonal_with_networking/outputs.tf
- examples/private_zonal_with_networking/test_outputs.tf
- examples/private_zonal_with_networking/variables.tf
- test/ci/private-zonal-with-networking.yml
- test/fixtures/private_zonal_with_networking/example.tf
- test/fixtures/private_zonal_with_networking/outputs.tf
- test/fixtures/private_zonal_with_networking/variables.tf
- test/integration/private_zonal_with_networking/controls/gcloud.rb
- test/integration/private_zonal_with_networking/controls/network.rb
- test/integration/private_zonal_with_networking/controls/subnet.rb
- test/integration/private_zonal_with_networking/inspec.yml
Creates an example that demonstrates creating a network and a private, zonal GKE cluster. 
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/308
Exposed  https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/309
> Private zonal example

- autogen/outputs.tf.tmpl
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster/outputs.tf
- modules/private-cluster-update-variant/outputs.tf
- modules/private-cluster/outputs.tf
- outputs.tf
Wait for resource, before endpoint is released, so other dependent components (like helm) are not going to use or access the cluster before it is ready.
> Cluster wait for resource

- Makefile
- autogen/cluster.tf.tmpl
- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- autogen/variables_defaults.tf
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- cluster.tf
- examples/node_pool/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster-update-variant/variables_defaults.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-private-cluster/variables_defaults.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
- modules/beta-public-cluster/variables_defaults.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster-update-variant/variables_defaults.tf
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- modules/private-cluster/variables_defaults.tf
- test/integration/deploy_service/controls/kubectl.rb
- variables.tf
- variables_defaults.tf
- fix #3
- fix #333 
- fix #334
The main idea of the PR is to move setting the dynamic default values for `node_pools_*` options into a separate step:
- `node_pools_labels`
- `node_pools_metadata`
- `node_pools_taints`
- `node_pools_tags`
- `node_pools_oauth_scopes`
Therefore I added a new file `autogen/variables_defaults.tf` the purpose of which is to setup the dynamic defaults for variables and shadow them with the locals of the same name.
I've also changed the example/test case `node_pools` -- it selectively sets `node_pools_*` options only for some pools. Also note the complete absense of the `node_pools_oauth_scopes` option in the example.
> Make node_pools_* params optional and allow pool-specific overrides.

- README.md
- autogen/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
- variables.tf
Updated "upstream_nameservers" variable type from "list" to list(string) for Terraform 0.12
> Updated "upstream_nameservers" variable type to list(string)

- .kitchen.yml
- examples/safer_cluster/README.md
- examples/safer_cluster/main.tf
- examples/safer_cluster/outputs.tf
- examples/safer_cluster/test_outputs.tf
- examples/safer_cluster/variables.tf
- examples/safer_cluster/versions.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/outputs.tf
- modules/safer-cluster/variables.tf
- modules/safer-cluster/versions.tf
- test/ci/safer-cluster.yml
- test/fixtures/safer_cluster/example.tf
- test/fixtures/safer_cluster/network.tf
- test/fixtures/safer_cluster/outputs.tf
- test/fixtures/safer_cluster/variables.tf
- test/integration/safer_cluster/controls/gcloud.rb
- test/integration/safer_cluster/inspec.yml
Still TODO: 
* add documentation; 
* add settings for customizing the project holding GCR
> Initial definition of a Safer Cluster module.

- autogen/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
This makes it less ambiguous how you should connect to private clusters for Terraform.
We also make sure to explicitly set the cluster endpoint output to the `public_endpoint` if `deploy_using_private_endpoint` is false.
> Add more detailed documentation for private cluster connectivity

- modules/acm/README.md
- modules/acm/main.tf
- modules/acm/variables.tf
> Add variable to allow a pre-generated SSH key to be passed to the ACM module

- autogen/main.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
> Compute region output for zonal clusters

- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
Related Issues: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/265 https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/398
Allow users to create node pools with different node_metadata config.
> Allow overriding node_metadata in node pools

- README.md
- autogen/main/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
> Document update variants

- autogen/main/scripts/wait-for-cluster.sh
- modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-private-cluster/scripts/wait-for-cluster.sh
- modules/beta-public-cluster/scripts/wait-for-cluster.sh
- modules/private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/private-cluster/scripts/wait-for-cluster.sh
- scripts/wait-for-cluster.sh
The gcloud --format command can be used instead of jq to extract the cluster status for this script.
I will submit a change for the delete-default-resource.sh script in another PR.
> Removing dependency on jq from wait-for-cluster.sh script

- autogen/main/variables.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/variables.tf
When attempting to use the variable pod_security_policy_config, as it has no specified type,
terraform interpret it has string, leading to errors such as 
```
Error: Invalid dynamic for_each value
on cluster.tf line 80, in resource "google_container_cluster" "primary":
80:     for_each = var.pod_security_policy_config
|----------------
| var.pod_security_policy_config is "[{\"enabled\":true}]"
```
As it expects a list of map, i specified the type accordingly.
I used any for the value type inside the map for future-proof reason.
Feel free to comment!
> Fixes pod_security_policy_config type issue

- README.md
- autogen/main/cluster.tf.tmpl
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
Issue: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/414
Fix: https://github.com/hashicorp/terraform/issues/22476#issuecomment-547689853
> Fix update-variants for_each splat, closes #414

- autogen/main/main.tf.tmpl
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
Provide a fix for #419 `Invalid index` error when creating a private cluster.
Closes #419
> Fix "Invalid index" creating private cluster

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/405
I've used the solution proposed by @apparentlymart in 
https://discuss.hashicorp.com/t/how-to-rewrite-null-resource-with-local-exec-provisioner-when-destroy-to-prepare-for-deprecation-after-0-12-8/4580
> Fix the warning about deprecated external references from destroy provisioners

- modules/workload-identity/main.tf
- modules/workload-identity/output.tf
- modules/workload-identity/variables.tf
In some cases, we want to attach workload identity to an existing Kubernetes Service Account. This updates the module to handle that case.
> Make workload identity k8s SA configurable

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
This adds support for creating alpha clusters.
Since this is a potentially dangerous option, I decided to *only* include it on beta clusters.
> feat: Add enable_kubernetes_alpha flag for beta clusters

- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/variables.tf
**TL;DR: Remove unused variable `service_account` in module `safer-cluster` to avoid confusion**
I found the document of `safer-cluster` a little bit confusing because there are two similar variables about worker nodes' service account:
1. `compute_engine_service_account`
2. `service_account`
After digging into the source code, I found the var `service_account` is unused but is the **same word** used in `main` module.
I think the former one is better understood so I remove the unused one to avoid confusion, even it's the same as the one used in `main`.
> Remove unused variable `service_account` in safer-cluster to avoid confusion

- auth.tf
- autogen/main/auth.tf.tmpl
- examples/workload_identity/main.tf
- modules/beta-private-cluster-update-variant/auth.tf
- modules/beta-private-cluster/auth.tf
- modules/beta-public-cluster/auth.tf
- modules/private-cluster-update-variant/auth.tf
- modules/private-cluster/auth.tf
Re-visting #429, the upstream issue has been resolved with 1.11.1 (terraform-providers/terraform-provider-kubernetes#759). This update sets the kubernetes provider version at or greater than the problematic version 1.11.0
Advancing to 1.11.1 also addresses terraform-providers/terraform-provider-kubernetes/issues/787 which was broken in kubernetes 1.10 and 1.11 and prevented running Terraform in a pod, ie Atlantis.
> update and pin kubernetes provider to >= 1.11.1

- autogen/safer-cluster/main.tf.tmpl
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster/main.tf
The Safer modules support regional and zonal clusters. However, the zones variable is never passed so the config errors when setting regional = false
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/449
> Fix zonal bug

- autogen/main/sa.tf.tmpl
- modules/beta-private-cluster-update-variant/sa.tf
- modules/beta-private-cluster/sa.tf
- modules/beta-public-cluster/sa.tf
- modules/private-cluster-update-variant/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
fixes #473 
- `roles/stackdriver.resourceMetadata.writer` is needed for stackdriver-metadata-agent  to send metadata as explained at the[ bottom of this page](https://cloud.google.com/monitoring/kubernetes-engine/observing).
> Add roles/stackdriver.resourceMetadata.writer to SA

- README.md
- autogen/main/main.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/main.tf
- modules/private-cluster/variables.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
- variables.tf
See https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/486
> [safer-cluster] Replace "kubernetes_version" with "release_channel"

- autogen/main/outputs.tf.tmpl
- examples/simple_regional_beta/README.md
- examples/simple_regional_beta/test_outputs.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster/outputs.tf
- test/fixtures/beta_cluster/outputs.tf
- test/integration/beta_cluster/controls/gcloud.rb
- test/integration/beta_cluster/inspec.yml
The identity namespace flag was "enabled". Changed the output value to reference the actual identity namespace of the cluster / the project.
This PR fixes #489.
> Fixes #489 Identity namespace output for beta clusters

- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/deploy_service/README.md
- examples/disable_client_cert/README.md
- examples/node_pool/README.md
- examples/shared_vpc/README.md
- examples/simple_regional/README.md
- examples/simple_regional_private/README.md
- examples/simple_zonal_private/README.md
- examples/simple_zonal_with_acm/README.md
- examples/stub_domains/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Expose node pool "shielded_instance_config" for module:
- beta-private-cluster
- beta-private-cluster-update-variant
- beta-public-cluster
- private-cluster
- private-cluster-update-variant
Tested for beta-private-cluster-update-variant
> Issue 501: Expose node pool "shielded_instance_config"

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
Issue: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/508
Done by editing the files under autogen/safer-cluster/ and running `make build`.
> Use the grant_registry_access variable in safer-cluster

- autogen/main/variables.tf.tmpl
- examples/simple_regional_beta/README.md
- examples/simple_regional_beta/main.tf
- examples/simple_regional_beta/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- test/fixtures/beta_cluster/main.tf
- test/fixtures/sandbox_enabled/example.tf
- test/integration/beta_cluster/controls/gcloud.rb
Fixes #490.
Since workload identity is enabled by default for beta-clusters, GKE_METADATA should be the default for exposing metadata to running pods as well in order to enabled workload identity in full.
> Enable GKE_METADATA_SERVER as node_metadata for beta-clusters (#490)

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
> Expose gce_pd_csi_driver for Safer Cluster modules #503

- autogen/main/cluster.tf.tmpl
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster/cluster.tf
Add support for boot_disk_kms_key for node pools that allows encrypting boot disks. Additional documentation available on https://cloud.google.com/kubernetes-engine/docs/how-to/using-cmek#gcloud_3
> Add boot_disk_kms_key variable for node pools

- modules/auth/main.tf
- modules/auth/outputs.tf
When cluster creation stalls out halfway, outputs will fail and block you out from plan/apply.
> fix: Update auth module to handle empty clusters

- modules/workload-identity/README.md
> chore: Generate docs for workload identity submodule

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/main/versions.tf.tmpl
- examples/node_pool/main.tf
- examples/node_pool_update_variant_beta/main.tf
- examples/safer_cluster/main.tf
- examples/simple_regional_beta/main.tf
- examples/simple_regional_private_beta/main.tf
- examples/workload_metadata_config/main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/beta-public-cluster/versions.tf
- test/setup/versions.tf
> Add KALM config

- autogen/main/main.tf.tmpl
- examples/simple_regional_beta/main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster/main.tf
- test/integration/beta_cluster/controls/gcloud.rb
Test that #535 doesn't occur.
Fixes #535.
> fix: Add additional guardrails for disabled workload identity.

- autogen/main/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
Docs on GKE authorized networks dont mention anywhere that IP must belong to Google network.
Ref: https://cloud.google.com/kubernetes-engine/docs/how-to/authorized-networks
> Remove incorrect note on whitelisting IPs

- README.md
- autogen/main/README.md
- docs/private_clusters.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
This should streamline docs a bit and make troubleshooting easier.
> chore: Relocate docs on private clusters to central location

- test/setup/main.tf
- test/setup/versions.tf
Test project creation using PF [can be flaky ](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/559#issuecomment-643247733)due to https://github.com/terraform-providers/terraform-provider-google/issues/6377
This bumps the provider to a version with the fix and also a newer PF version.
> Fix CI test project creation issue

- modules/workload-identity/README.md
Uses `project_id` over `project` as per inputs.
> Update workload-identity docs

- .gitignore
- .kitchen.yml
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- examples/simple_regional_with_asm/README.md
- examples/simple_regional_with_asm/main.tf
- examples/simple_regional_with_asm/outputs.tf
- examples/simple_regional_with_asm/test_outputs.tf
- examples/simple_regional_with_asm/variables.tf
- examples/simple_regional_with_asm/versions.tf
- modules/asm/README.md
- modules/asm/main.tf
- modules/asm/outputs.tf
- modules/asm/scripts/gke_hub_registration.sh
- modules/asm/scripts/install_asm.sh
- modules/asm/scripts/kubectl_wrapper.sh
- modules/asm/variables.tf
- test/fixtures/simple_regional_with_asm/example.tf
- test/fixtures/simple_regional_with_asm/network.tf
- test/fixtures/simple_regional_with_asm/outputs.tf
- test/fixtures/simple_regional_with_asm/variables.tf
- test/integration/simple_regional_with_asm/controls/gcloud.rb
- test/integration/simple_regional_with_asm/controls/kubectl.rb
- test/integration/simple_regional_with_asm/inspec.yml
- test/setup/iam.tf
- test/setup/main.tf
- Adds ASM module
- Downloads and installs ASM
- Produces ASM resource patch yamls
- Optionally enables registration to GKE Hub
- Adds example with ASM module
- Adds tests for ASM module
TODO:
> Add ASM module

- .kitchen.yml
- autogen/main/cluster.tf.tmpl
- autogen/main/firewall.tf.tmpl
- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- examples/safer_cluster/main.tf
- modules/beta-private-cluster-update-variant/firewall.tf
- modules/beta-private-cluster/firewall.tf
- modules/private-cluster-update-variant/firewall.tf
- modules/private-cluster/firewall.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
- test/integration/safer_cluster/controls/network.rb
- test/integration/safer_cluster/inspec.yml
> Add firewall support safer-cluster modules

- examples/workload_identity/main.tf
- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/scripts/kubectl_wrapper.sh
- modules/workload-identity/variables.tf
fixes #555 
- Adds kubectl_wrapper
- Adds overwrite flag for annotate command
- Update docs
> Enhance WI module usability with existing KSA

- autogen/safer-cluster/README.md
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster/README.md
- Fixed typo in `autogen/safer-cluster/README.md`
- ran `make build` to regenerate related files
> fix: Typo in autogen/safer-cluster/README.md

- autogen/main/cluster.tf.tmpl
- autogen/main/versions.tf.tmpl
- examples/node_pool/main.tf
- examples/node_pool_update_variant/main.tf
- examples/node_pool_update_variant_beta/main.tf
- examples/regional_private_node_pool_oauth_scopes/provider.tf
- examples/safer_cluster/main.tf
- examples/safer_cluster_iap_bastion/cluster.tf
- examples/safer_cluster_iap_bastion/provider.tf
- examples/simple_regional_beta/main.tf
- examples/simple_regional_private_beta/main.tf
- examples/simple_zonal_with_asm/main.tf
- examples/workload_metadata_config/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/versions.tf
- test/fixtures/sandbox_enabled/example.tf
- test/integration/node_pool/controls/gcloud.rb
Fixes #593
BREAKING CHANGE: Minimum provider version for beta modules increased to v3.29.0.
> fix: Explicitly specify VPC-native clusters for beta modules.

- docs/upgrading_to_v10.0.md
Release PR: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/595
> Add v10.0 upgrade doc

- autogen/main/cluster.tf.tmpl
- autogen/main/dns.tf.tmpl
- cluster.tf
- dns.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/dns.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/dns.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/dns.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/dns.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/dns.tf
- modules/private-cluster/cluster.tf
- modules/private-cluster/dns.tf
Old version wasn't working with version gcloud installed via `apt-get install` as it  is always trying to `gcloud component install`
> Bump gcloud module to 1.3.0

- modules/asm/README.md
- modules/asm/main.tf
- modules/asm/scripts/install_asm.sh
- modules/asm/variables.tf
- allow user to specify ASM dir to allow deploys to different clusters from same config
- allow user to specify ASM version
> Parameterize ASM to allow multiple deploys

- autogen/main/versions.tf.tmpl
- autogen/safer-cluster/versions.tf.tmpl
- examples/safer_cluster/versions.tf
- examples/simple_regional_beta/versions.tf
- examples/simple_regional_private_beta/versions.tf
- examples/simple_zonal_with_asm/versions.tf
- examples/stub_domains_upstream_nameservers/versions.tf
- examples/upstream_nameservers/versions.tf
- examples/workload_metadata_config/versions.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/versions.tf
- modules/safer-cluster-update-variant/versions.tf
- modules/safer-cluster/versions.tf
- test/fixtures/stub_domains_upstream_nameservers/versions.tf
- test/fixtures/upstream_nameservers/versions.tf
- test/fixtures/workload_metadata_config/versions.tf
- test/integration/simple_zonal_with_asm/controls/gcloud.rb
- test/setup/versions.tf
- versions.tf
- relax version constraint to allow usage with 0.13
- Kitchen tests [run with `v0.13.0-rc1`](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/88017ad3bc0d40473ac3d94546660328aeee878d) 
- All tests pass except `safer_cluster`, `private_zonal_with_networking`, `simple_regional_with_networking`, `safer_cluster_iap_bastion` due to dependencies on other modules with version constraints
- module `for_each` and `depends_on` spot checked and seems to be working without issues
- small fix for GKE hub gcloud command
> chore: relax tf version to allow 0.13

- examples/simple_zonal_with_acm/main.tf
- modules/acm/README.md
- modules/acm/main.tf
- modules/acm/templates/acm-config.yml.tpl
- modules/acm/variables.tf
- modules/config-sync/README.md
- modules/config-sync/main.tf
- modules/config-sync/templates/config-sync-config.yml.tpl
- modules/config-sync/variables.tf
- modules/k8s-operator-crd-support/main.tf
- modules/k8s-operator-crd-support/variables.tf
- test/integration/simple_zonal/controls/gcloud.rb
This commit contains the new features in ACM/ Config Sync:
1. sourceFormat option.
2. hierarchyController.
3. logDeniesEnabled in Policy Controller.
Testing being ran by linde@
> Update fields for ACM and Config Sync to bring them to feature parity

- autogen/main/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
- Docs in #654 seems to have not been added to autogen and bot failed to catch that (will investigate seperately), although linter failed
- Following #653 make link to private cluster docs absolute
> fix: docs generation, update private cluster docs to absolute

- README.md
- autogen/main/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
Fixed the following typo across all affected README.md files:
Sub modules are provided *from* --> Sub modules are provided *for*
> Fix minor typo in README.md files: from --> for

- modules/asm/README.md
- modules/asm/main.tf
- modules/asm/variables.tf
Default service account will not necessarily have the required permissions to run kubectl commands. Expose service_account_key_file variable from kubectl_wrapper module to use with ASM module.
> Expose service account variable

- examples/simple_zonal_with_asm/hub.tf
- modules/asm/README.md
- modules/asm/main.tf
- modules/asm/outputs.tf
- modules/asm/variables.tf
> refactor!:remove hub from asm module

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/integration/beta_cluster/controls/gcloud.rb
- test/integration/safer_cluster/controls/gcloud.rb
IIUC we should set `enabled = false` when `skip_provisioners = true`. Looks like a regression from #404
> fix: Fix skip_provisioners enabled flag for wait_for_cluster

- autogen/main/scripts/wait-for-cluster.sh
- modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-private-cluster/scripts/wait-for-cluster.sh
- modules/beta-public-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-public-cluster/scripts/wait-for-cluster.sh
- modules/private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/private-cluster/scripts/wait-for-cluster.sh
- scripts/wait-for-cluster.sh
The status is PROVISIONING at the beginning, thus the original logic will always exit and say "Cluster is ready!". If we wait for the RUNNING status, we will know for sure the cluster is up.
Note: if the initial cluster node pool is removed it will say RUNNING for a second then go back to RECONCILING again while the node pool is removed. This might cause issues as well.
> Make wait-for-cluster logic more robust

- modules/k8s-operator-crd-support/main.tf
Module failed as it tried to create `git-creds` secret regardless of secret type. Add enabled flag to k8sop_creds_secret module.
> ACM submodule: fix bug when not using `ssh` secret type

- autogen/main/main.tf.tmpl
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster/main.tf
I have been testing some changes with zonal clusters, but receive this error:
```
Error: error creating NodePool: googleapi: Error 400: Auto_upgrade cannot be false when release_channel REGULAR is set., badRequest
```
The node pools I define do have autoupgrade enabled, but I think the default node pool (which I am deleting with `remove_default_node_pool` anyway) is the problem node pool. Regional clusters already have auto-upgrade enabled by default, so I'm guessing nobody has used the specific combination of a zonal cluster and release channels with this module yet.
This [is noted in the documentation](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#new-cluster) as a disallowed configuration:
> Note: Node auto-upgrade and auto-repair are enabled and cannot be …
> Enable auto-upgrade in beta clusters with a release channel

- README.md
- autogen/main/README.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster/README.md
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster/README.md
- modules/private-cluster-update-variant/README.md
- modules/private-cluster/README.md
This PR fixes a broken link to the examples folder that appears in all `README.md` files.
Replacing:
[https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/examples/](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/examples/)
With:
[https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples)
> Fix broken link in README.md

- modules/asm/main.tf
- modules/asm/scripts/install_asm.sh
fixes #683 
Spot checked for `release-1.6-asm` by enabling sidecar injection, deploying workload and checking that `ISTIO_META_MESH_ID:` is set correctly.
> fix: set project number for ASM install 

- modules/acm/README.md
- modules/acm/outputs.tf
- modules/hub/README.md
- modules/hub/main.tf
- modules/hub/variables.tf
- modules/k8s-operator-crd-support/main.tf
- modules/k8s-operator-crd-support/outputs.tf
- modules/k8s-operator-crd-support/scripts/wait_for_gatekeeper.sh
While using the hub submodule we ran into issues where if ACM was installed on a cluster with policy controller enabled (currently default behavior), gatekeeper would cause issues if it were not ready prior to hub registration or ASM install.
This PR does the following:
1. Added a `kubectl_wrapper` to ACM module with a `wait_for_gatekeeper.sh` script that ensures that the deployment and service that cause issues with ASM and Hub are ready.
2. Exposed a wait variable for ACM that is either the operator being deployed or wait_for_gatekeeper.sh reporting both are ready.
3. Exposed module_depends_on variable for Hub module to be able to add the acm.wait variable there.
> ACM: Wait for gatekeeper & Hub: expose module_depends_on

- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
> Workload Identity: allow passing roles to created service account

- modules/binary-authorization/main.tf
Updated the Project Services module version to 9.2.0 so the Binary Authorization module supports Terraform 0.13
> Updating the project services version for Binary Authorization

- autogen/main/cluster.tf.tmpl
- autogen/main/scripts/wait-for-cluster.sh
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/scripts/wait-for-cluster.sh
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/scripts/wait-for-cluster.sh
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/private-cluster/cluster.tf
- modules/private-cluster/scripts/wait-for-cluster.sh
- scripts/wait-for-cluster.sh
fixes: #733 
Changes:
- match on equality `key=value`  instead of pattern `key:pattern` using both cluster name and location
- if  `current_status` is empty, i.e filter did not match any cluster, exit with error
> fix: multiple cluster wait-for-cluster.sh

- autogen/main/scripts/wait-for-cluster.sh
- modules/beta-private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-private-cluster/scripts/wait-for-cluster.sh
- modules/beta-public-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/beta-public-cluster/scripts/wait-for-cluster.sh
- modules/private-cluster-update-variant/scripts/wait-for-cluster.sh
- modules/private-cluster/scripts/wait-for-cluster.sh
- scripts/wait-for-cluster.sh
fixes #735 
- fallback to just using name in the filter if location is not set for destroy hook
> fix: wait-for-cluster fallback filter to name if location is not set

- autogen/main/main.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
Exposes [`cloudrun_config.load_balancer_type`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#load_balancer_type) when configuring beta clusters.
> Add support for Cloud Run load balancer configuration

- autogen/main/versions.tf.tmpl
- autogen/safer-cluster/versions.tf.tmpl
- examples/safer_cluster/versions.tf
- examples/simple_regional_beta/versions.tf
- examples/simple_regional_private_beta/versions.tf
- examples/simple_zonal_with_asm/versions.tf
- examples/stub_domains_upstream_nameservers/versions.tf
- examples/upstream_nameservers/versions.tf
- examples/workload_metadata_config/versions.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/versions.tf
- modules/safer-cluster-update-variant/versions.tf
- modules/safer-cluster/versions.tf
- test/fixtures/stub_domains_upstream_nameservers/versions.tf
- test/fixtures/upstream_nameservers/versions.tf
- test/fixtures/workload_metadata_config/versions.tf
- test/setup/versions.tf
- versions.tf
This PR adds support for terraform 0.14. similar to [terraform-google-project-factory/pull/505](https://github.com/terraform-google-modules/terraform-google-project-factory/pull/505) as mentioned in [issues/754](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/754)
> remove version constraint

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
As vertical autoscaling exists also in terraform google provider, this PR adds vertical pod autoscaling for every cluster.
I just changed cluster.tf.tmpl and variables.tf.tmpl and do `make build`.
Feel free to comment if there is something wrong.
> feat: Add vertical autoscaling to GA clusters

- README.md
- autogen/main/outputs.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/outputs.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/outputs.tf
- modules/private-cluster/README.md
- modules/private-cluster/outputs.tf
- outputs.tf
This PR adds a new output called `instance_group_urls` - List of instance group URLs which have been assigned to the cluster.
See: https://www.terraform.io/docs/providers/google/r/container_cluster.html#instance_group_urls
> feat: Add instance_group_urls output

- autogen/main/cluster.tf.tmpl
- autogen/main/sa.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/sa.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/sa.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/sa.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/sa.tf
- modules/private-cluster-update-variant/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
- test/integration/node_pool/controls/gcloud.rb
This sets the Service Account that should be used by node VMs created by
node auto-provisioning. This should cause the auto-provisioned nodes to
have the same permissions as the nodes that are manually provisioned.
This is to address #560. I will be testing this in my cluster that has NAP enabled. As far as I can tell, it's safe to set this value whether auto-provisioning is actually enabled or disabled, and that using `local.service_account` is the right default. That's the default for any manual `node_pool` that isn't specifically overridden.
> Set auto_provisioning_defaults.service_account

- auth.tf
- autogen/main/auth.tf.tmpl
- autogen/main/versions.tf.tmpl
- examples/workload_identity/main.tf
- modules/beta-private-cluster-update-variant/auth.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/auth.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/auth.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/auth.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/auth.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/auth.tf
- modules/private-cluster/versions.tf
- versions.tf
Terraform 0.14 shows warnings of the following kind asking to move the provider version constraint to required_providers block.
> Move version constraint to required_providers block

- examples/node_pool_update_variant_public_beta/README.md
- examples/node_pool_update_variant_public_beta/data/shutdown-script.sh
- examples/node_pool_update_variant_public_beta/main.tf
- examples/node_pool_update_variant_public_beta/outputs.tf
- examples/node_pool_update_variant_public_beta/test_outputs.tf
- examples/node_pool_update_variant_public_beta/variables.tf
As asked for in #546 (@morgante), this adds an example for the beta-public-update-variant module.
I copied the node_pool_update_variant_beta and removed the variables that do not exist.
Not quite sure if this works & is the way to go to be honest :-)
> Add example for public beta upgrade variant

- docs/upgrading_to_v13.0.md
- modules/k8s-operator-crd-support/main.tf
Creating a local file `operator_cr.yaml` in an ephemeral pipeline during create results in an error during subsequent destroy if that file is not present.
This PR aims to pass the rendered yaml via stdin.
> feat!: dynamic operator yaml

- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
This PR adds the option to disable Kubernetes SA annotation in the workload-identity module. This is useful in cases where an operator managing IAM doesn't have access to GKE or environments where GKE is managed in a declarative manner through GitOps, for example.
> Add the option to disable Kubernetes SA annotation in workload-identity.

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Hello,
Creating a zonal cluster will fail with a
```
Error: Invalid template interpolation value
on .terraform/modules/gke_private/modules/beta-private-cluster/cluster.tf line 52, in resource "google_container_cluster" "primary":
52:   subnetwork = "projects/${local.network_project_id}/regions/${var.region}/subnetworks/${var.subnetwork}"
|----------------
| var.region is null
The expression result is null. Cannot include a null value in a string
template.
```
The bug seems here [https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/bf4d0da796f3df0e5d924ab04c701df0a239e341/modules/beta-private-cluster/cluster.tf#L52](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/bf4d0da796f3df0e5d924ab04c701df0a239e341/modules/beta-private- …
> Fix: Can't create zonal beta-private cluster is region not set.

- README.md
- autogen/main/README.md
- autogen/main/variables.tf.tmpl
- docs/upgrading_to_v14.0.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
- test/integration/beta_cluster/controls/gcloud.rb
- test/integration/private_zonal_with_networking/controls/gcloud.rb
- test/integration/sandbox_enabled/controls/gcloud.rb
- test/integration/simple_regional/controls/gcloud.rb
- test/integration/simple_regional_private/controls/gcloud.rb
- test/integration/simple_regional_with_kubeconfig/controls/gcloud.rb
- test/integration/simple_regional_with_networking/controls/gcloud.rb
- test/integration/simple_zonal/controls/gcloud.rb
- test/integration/simple_zonal_private/controls/gcloud.rb
- test/integration/stub_domains/controls/gcloud.rb
- test/integration/stub_domains_private/controls/gcloud.rb
- test/integration/stub_domains_upstream_nameservers/controls/gcloud.rb
- test/integration/upstream_nameservers/controls/gcloud.rb
- variables.tf
This PR fixes #804.
The only thing I'm not sure about is whether or not the `network_policy` checks are necessary in the `stub` integration tests (`stub_domains`, `stub_domains_private`, `stub_domains_upstream_nameservers`).
> Fix: Change default value of network_policy variable to false

- modules/auth/README.md
- modules/auth/main.tf
- modules/auth/variables.tf
This fixes #828 on the `auth` module. A new flag `use_private_endpoint` is introduced. If this flag is set to `true`, the `private_endpoint` property of the GKE cluster is looked up.
If `use_private_endpoint` is set to `false` (default), the `data.google_container_cluster.gke_cluster.private_cluster_config[0].public_endpoint` will be used if available with a fallback to the default GKE `endpoint` property.
> Add new property to explicitly return GKE private_endpoint

- docs/upgrading_to_v13.0.md
Add section to v13.0 upgrade doc on how to workaround `random_id` and nodepool cycling mentioned in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/842
> Add step to avoid nodepool replacement due to random-id change

- modules/k8s-operator-crd-support/main.tf
Hi,
currently the spec.hierarchyController definition is not working for the ConfigManagement template in the acm and config-sync modules.
The PR fixes the following things:
* hierarchy_controller is renamed to hierarchyController in the resource definition
* quotation marks added by the yamlencode function are removed
* correct indentation with more than one entry in the hiearchy_controller variable
With the hierarchy_controller variable defined as:
```
hierarchy_controller = {
enabled                         = true
enablePodTreeLabels             = true
enableHierarchicalResourceQuota = true
}
```
the output with v14.0.1 is as follows:
```
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
name: config-management
spec:
clusterName: test
policyController:
git: …
```
> Fix ConfigManagement hierarchyController definition

- README.md
- autogen/main/firewall.tf.tmpl
- autogen/main/variables.tf.tmpl
- firewall.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/firewall.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/firewall.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/firewall.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/firewall.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/firewall.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/firewall.tf
- modules/private-cluster/variables.tf
- variables.tf
Resolves #880 
- Flag controls exclusive creation of a firewall rule for ports defined in firewall_inbound_ports
- The existing flag add_cluster_firewall_rules is kept on the firewall rule resource for backwards compatibility
> Introduce flag add_master_webhook_firewall_rules

- README.md
- autogen/main/main.tf.tmpl
- autogen/main/outputs.tf.tmpl
- autogen/safer-cluster/outputs.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/outputs.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster-update-variant/outputs.tf
- modules/private-cluster/README.md
- modules/private-cluster/main.tf
- modules/private-cluster/outputs.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/outputs.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/outputs.tf
- outputs.tf
This PR adds the [GKE Cluster id](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#id) as an output. Having the id handy saves users from having to fetch that id with a data source.
Additionally, this is likely a prerequisite for #860 
Closes #885
> Add cluster ID to outputs

- modules/workload-identity/README.md
- modules/workload-identity/output.tf
I wanted to access the id
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account#attributes-reference
but instead of adding it individually, exporting the GSA as is offers
the most flexibility long term.
Signed-off-by: naseemkullah <naseem@transit.app>
> [workload identity] add entire GSA in output

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/main/versions.tf.tmpl
- examples/node_pool/main.tf
- examples/node_pool_update_variant_beta/main.tf
- examples/node_pool_update_variant_public_beta/main.tf
- examples/regional_private_node_pool_oauth_scopes/provider.tf
- examples/safer_cluster/main.tf
- examples/safer_cluster_iap_bastion/provider.tf
- examples/simple_regional_beta/main.tf
- examples/simple_regional_private_beta/main.tf
- examples/simple_zonal_with_asm/main.tf
- examples/workload_metadata_config/main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/beta-public-cluster/versions.tf
- test/bundle.hcl
Adds support for the `google_container_cluster` [enable_l4_ilb_subsetting](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_l4_ilb_subsetting) flag, which is particularly useful for [clusters that require more than 250 total Nodes and build ILBs](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#limits).
Note that `enable_l4_ilb_subsetting` is only supported in `google-beta >= 3.63.0`. Minimum module versions are bumped in accordance with this version change.
> feat!: Add support for `enable_l4_ilb_subsetting` flag

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
This addresses #899 by adding a new local_ssd_ephemeral_count attribute to the node_pool configuration.  This gets passed conditionally to a new `ephemeral_storage_config` block on the `google_container_node_pool` resource.
This is supported only on the google-beta provider, since 3.60.0, and is a beta feature in GKE 1.18 and later.
Feature and its use is documented [here](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/local-ssd).
Mutually Exclusive Configs:
Both local_ssd_count and local_ssd_ephemeral_count cannot be used on the same node pool, an error will return:
`Error: error creating NodePool: googleapi: Error 400: Can not use local SSDs as volumes when using ephemeral storage backed by local SSDs., badRequest`
> Add use local_ssd_ephemeral_count attribute in node_pool config (beta)

- autogen/main/dns.tf.tmpl
- dns.tf
- modules/asm/README.md
- modules/asm/main.tf
- modules/asm/variables.tf
- modules/beta-private-cluster-update-variant/dns.tf
- modules/beta-private-cluster/dns.tf
- modules/beta-public-cluster-update-variant/dns.tf
- modules/beta-public-cluster/dns.tf
- modules/hub/main.tf
- modules/k8s-operator-crd-support/main.tf
- modules/k8s-operator-crd-support/variables.tf
- modules/private-cluster-update-variant/dns.tf
- modules/private-cluster/dns.tf
- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
Continuation of https://github.com/terraform-google-modules/terraform-google-gcloud/pull/91.  Resolves #874 and #879
**NOTES:**
* In order to make this easier to review, I have separated the commits based on changes per module, i.e.: one for all the gke modules, one for workload identity module, one for asm module, one for k8s-operator-crd-support, etc.
> Bump up kubectl-wrapper and gcloud module version to add ability to impersonate service account

- autogen/main/variables.tf.tmpl
- examples/simple_regional_beta/README.md
- examples/simple_regional_beta/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
Hi, [the description of `datapath_provider`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#datapath_provider) might be lacking in explanation.
So, I added a description about `ADVANCED_DATAPATH`.
> Add a description about `ADVANCED_DATAPATH`

- examples/simple_zonal_with_asm/outputs.tf
- modules/asm/main.tf
Currently, the ASM module’s destroy command only removes the istio-system namespace. This pull request extends the module’s destroy command to remove any istio/asm related labels and/or namespaces.
For testing my changes, I used the "simple_zonal_with_asm" example. Unfortunately, the example didn't start due to the ca_certificate output variable not being marked as sensitive. After correcting this mistake, everything was working as expected.
Fixes #881
> Fixed the ASM module's destroy command.

- modules/asm/main.tf
- modules/asm/scripts/destroy_asm.sh
- test/integration/node_pool/controls/gcloud.rb
fixes #919 
also adds `--ignore-not-found` incase a namespace is not found. This could be useful if destroy failed midway due to any reason and only removed one of the namespaces.
> fix: asm destroy

- modules/asm/scripts/install_asm.sh
Similar to the fix @ameer00 and I made for `KEY_FILE_COMMAND_SNIPPET` to add the full path to the service account key file, the `CUSTOM_OVERLAYS_COMMAND` also needs the full path since the script generating the command is in a different location from where it is used, so it will not resolve relative paths correctly.
> Asm overlay path

- modules/asm/main.tf
`kustomize` seems to be a historical requirement, and is not used anymore by the ASM install script - https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/asm/scripts/install_asm.sh.
The install works fine without `kustomize` command being available on the system.
> fix: Remove kustomize requirement

- modules/asm/main.tf
Added mechca.googleapis.com to the set of APIs that need to be enabled for ASM installation.
> fix: updated GCP APIs in ASM module

- test/integration/node_pool/controls/gcloud.rb
[default](https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd#:~:text=starting%20with%20gke%20node%20version%201.19) is now cos_containerd
> fix: nap default image in test

- CONTRIBUTING.md
- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/output.tf
- modules/workload-identity/variables.tf
Resolves https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/956.
The workload-identity module currently allows for reusing an existing KSA, but not an existing GSA. This is a common requirement for us: typically, we will have two clusters within the same project (for example, a production cluster and a disaster recovery cluster), and want to configure KSAs in each cluster that are bound to the same GSA.
With the existing module, this isn't possible, as errors are thrown owing to the attempt to recreate an existing GSA.
This is a work-in-progress: I believe it's feature complete, but I'm still testing.
> Enables an existing GSA to be used when setting up Workload Identity

- modules/workload-identity/main.tf
fixes #959 to prevent unnecessary delete recreate
> fix: restore WI GSA resource name

- examples/workload_identity/README.md
- examples/workload_identity/main.tf
- examples/workload_identity/outputs.tf
- modules/workload-identity/main.tf
- test/fixtures/workload_identity/outputs.tf
- test/integration/workload_identity/controls/gcloud.rb
- test/integration/workload_identity/inspec.yml
fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/971
Improves tests for different modes default, with existing KSA, with existing GSA
Permadiff issues should be caught by the new framework once we switch over.
> fix: WI conditionally invoke data source if using external GSA

- modules/workload-identity/main.tf
> fix: Use provided gcp_given_name for workload identity

- build/int.cloudbuild.yaml
- test/fixtures/node_pool/network.tf
- test/integration/node_pool/controls/gcloud.rb
Tests using the ruby k8s client seem to be failing with `Permission bits for '/builder/home/.netrc' should be 0600, but are 644`.
> chore: fix test .netrc permissions, nodepool pod range fixture

- autogen/main/cluster.tf.tmpl
- autogen/main/main.tf.tmpl
- examples/node_pool/main.tf
- examples/node_pool_update_variant/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/main.tf
- test/integration/node_pool/controls/gcloud.rb
Issue [https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/240](url) was resolved but now all node pools needs to be with gVisor or non of them.
With this PR you are able to define `sandbox_enabled` variable per node pool, code is backward compatible.
> feat: Add support for gVisor per node pool

- examples/workload_identity/outputs.tf
- modules/workload-identity/output.tf
> fix: WI GCP SA output

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
This PR adds some security relevant settings to the default node pool that exists temporarily during cluster creation to satisfy Terraform Enterprise Sentinel policies defined by CSO at my project.
> Set security relevant settings on default node pool to comply with Sentinel

- README.md
- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
- test/integration/workload_metadata_config/controls/gcloud.rb
- variables.tf
Mainly documentation changes, but I added a small change to a test to see if the role is properly assigned. Let me know if I should add anything else.
Issue reference: #1015
> Document and test var.grant_registry_access supports artifact registry

- examples/workload_identity/main.tf
- modules/workload-identity/README.md
This is a tiny doc update that adds a `depends_on` block to the Workload Identity README example for existing GSA, as discussed in #1059. This makes the README example match the `examples/workload_identity` module & prevents Terraform from trying to read the GSA data source before it is created.
> nit: update Workload Identity README example for existing GSA

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/node_pool/main.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- test/integration/node_pool/controls/gcloud.rb
Fix for #1045. The `gpu_partition_size` field behaves unexpectedly and is required, not optional, in provider versions 3.90+, so we default to `null` as a workaround.
I was also thinking about adding a test, but I'm not sure how to approach it. The accelerator types supported by the machine and location in the example `node_pool` do not allow GPU partitioning (I specifically tried `nvidia-tesla-k80` and `nvidia-tesla-a100`). Would this require a new example?
> feat: Add support for `gpu_partition_size`

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Fixes #1008 
This PR simply makes the auto-provisioning defaults block not beta-exclusive, but I also want to add the `min_cpu_platform` argument in the block as specified [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_auto_provisioning_defaults) since it seems we added the feature for default node pools in #1057. However, I don't understand why we pull the value from the first node pool using `lookup(var.node_pools[0],...)` because, from what I understand, `min_cpu_platform` is a cluster-level variable, so it feels weird to read from a specific node pool's arguments, like `pool-01`, even though it will apply to other node pools as well. Shouldn't it be its own variable and read in like `var.min_cpu_platform` or something …
> feat: Make auto_provisioning_defaults a non-beta feature

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
- test/integration/safer_cluster/controls/gcloud.rb
First time contributor implementing https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1064
Default safer-cluster to Dataplane V2 with
```
datapath_provider = "ADVANCED_DATAPATH"
```
But allow module consumers to set V1 as a fallback via a module variable, as upgrading to Dataplane V2 requires cluster re-creation.
> Default datapath_provider to ADVANCED_DATAPATH (aka. Dataplane V2) for safer-cluster with variable for fallback

- modules/auth/main.tf
- modules/auth/outputs.tf
> Removed dependency to obsolete template_file by upgrading to templatefile

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Addresses #1118.
This will apply the following tags to the default node pool:
* the [`cluster_network_tag`](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/c2dbc6f8aabbfc722a56e6a56e7121e3fbe6826a/autogen/main/main.tf.tmpl#L167) (`gke-${var.name}`)
* the pool variant of the `cluster_network_tag` (`gke-${var.name}-default-pool`)
* user-specified tags in `var.node_pools_tags["all"]`
* user-specified tags in `var.node_pools_tags["default-pool"]`
This may be needed for private clusters in VPC networks with a "default-deny-all" firewall rule that use network tags to define exceptions for e.g., egress to the `master_ipv4_cidr_block`.
Two quick notes/questions:
* I deviated slightly from @morgante's [suggestion](https://github.com/terraform-google-modules/terra …
> Allow users to specify network tags for the default node pool

- autogen/main/firewall.tf.tmpl
- modules/beta-private-cluster-update-variant/firewall.tf
- modules/beta-private-cluster/firewall.tf
- modules/beta-public-cluster-update-variant/firewall.tf
- modules/beta-public-cluster/firewall.tf
Addresses #1124.
I bumped into this when trying to create a `safer-cluster` in a VPC network with a default deny egress rule. The `intra_egress` firewall rule was required to allow the default pool to report back to the control plane so it could be deleted (as part of the `google_container_cluster.primary` create operation).
However, the `intra_egress` firewall rule had a Terraform dependency on the `google_container_cluster.primary` resource, so it was never created, preventing the cluster from creating successfully.
This PR simply creates a separate rule for egress to the `tpu_ipv4_cidr_block`, allowing the `intra_egress` rule to get created before the `google_container_cluster` resource.
> fix: Create separate firewall rule for egress to TPUs

- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/versions.tf.tmpl
- docs/upgrading_to_v18.0.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/versions.tf
- test/setup/versions.tf
> Add spot vm support to beta clusters

- docs/upgrading_to_v19.0.md
Next major release version is v19 while the guide referenced 18.
> chore: fix upgrade guide version

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- docs/upgrading_to_v19.0.md
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- test/integration/node_pool/controls/gcloud.rb
I've changed the default image_type.
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1069
> feat!: Change default node image from COS to COS_CONTAINERD

- autogen/main/main.tf.tmpl
- autogen/main/outputs.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/main.tf
- modules/beta-autopilot-private-cluster/outputs.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/main.tf
- modules/beta-autopilot-public-cluster/outputs.tf
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/outputs.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/variables.tf
- variables.tf
> chore: cleanup unused autopilot vars

- modules/asm/main.tf
[In autopilot clusters,] subsequent terraform runs overwrite the `ASM_OPTS: "CNI=on"` value in the asm_option config map. This prevents new or restating workloads from being scheduled as the proxy tries to cap add NET_ADMIN on start. This PR conditionally adds the expected setting.
> Apply applicable ASM_OPTS in config_map

- autogen/main/main.tf.tmpl
- autogen/main/outputs.tf.tmpl
- examples/simple_zonal_with_asm/main.tf
- main.tf
- modules/asm/README.md
- modules/beta-autopilot-private-cluster/main.tf
- modules/beta-autopilot-private-cluster/outputs.tf
- modules/beta-autopilot-public-cluster/main.tf
- modules/beta-autopilot-public-cluster/outputs.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/outputs.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster-update-variant/outputs.tf
- modules/private-cluster/main.tf
- modules/private-cluster/outputs.tf
- outputs.tf
Fixes #1181.
Change to the `simple_zonal_with_asm` module is just to get a passing run in CI with a static cluster name.
> Make GKE module cluster_name computed attribute

- examples/safer_cluster_iap_bastion/README.md
- examples/safer_cluster_iap_bastion/variables.tf
Fixes [#1155](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1155)
> Removed unused variable ip_source_ranges_ssh from example safer_cluster_iap_bastion

- modules/asm/README.md
Expands the independent ASM submodule documentation example to include the requirement to configure the Kubernetes Provider for the target cluster.   Without configuration the Kubernetes Provider silently falls back to localhost rather than a raising a warning or error. #1208
> docs: Expand independent ASM submodule example req

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
> Add support for image streaming/GCFS

- modules/asm/versions.tf
This makes it so that if a user wants to create multiple clusters in a single application, they can pass a provider alias into the module to install ASM on both.
Example:
```
provider "kubernetes" {
host                   = "https://${google_container_cluster.alpha.endpoint}"
token                  = data.google_client_config.default.access_token
cluster_ca_certificate = base64decode(google_container_cluster.alpha.master_auth[0].cluster_ca_certificate)
alias                  = "cluster-alpha"
}
provider "kubernetes" {
host                   = "https://${google_container_cluster.beta.endpoint}"
token                  = data.google_client_config.default.access_token
cluster_ca_certificate = base64decode(google_container_cluster.beta.master_auth[0].cluster_ca_certificate)
alias …
```
> Add required kubernetes provider to ASM module

- autogen/safer-cluster/main.tf.tmpl
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster/main.tf
Set `initial_node_count` to `1` if `0` supplied in safer-cluster [inline with TPG documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster) for the opinionated `remove_default_node_pool=true`.
> fix: set initial_node_count with remove_default_node_pool

- examples/node_pool/main.tf
- examples/node_pool_update_variant/main.tf
- examples/node_pool_update_variant_beta/main.tf
- examples/node_pool_update_variant_public_beta/main.tf
- examples/regional_private_node_pool_oauth_scopes/main.tf
- examples/safer_cluster_iap_bastion/apis.tf
- examples/simple_regional_private/main.tf
- test/fixtures/sandbox_enabled/example.tf
- test/fixtures/simple_zonal/outputs.tf
- test/integration/node_pool/controls/gcloud.rb
- test/integration/simple_autopilot_private/controls/gcloud.rb
Fix #1247 
Fix #1249 
Fix #1245
> fix: various fix to address CI issues

- modules/workload-identity/main.tf
As per noted regexp, the service account name cannot end with a dash.
This can happen when the name is over 30 characters long
and so a substring is extracted, but the 30th character happens to be a
dash.
> fix: trim trailing dash from gcp SA name in WorkloadIdentity

- autogen/main/cluster.tf.tmpl
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
As changing the enable_secure_boot config currently forces a replacement of
the node pool, see:
https://github.com/hashicorp/terraform-provider-google/blob/5290a9f74d491bd3a05c32cdc60773ac6c53d4ae/google/node_config.go#L217
Fixes #1276
> Add keeper for `enable_secure_boot` nodepool option for update variant.

- modules/asm/README.md
Now that the ASM module is not using the `install_asm` or the `asmcli`, the users need to manually set the `mesh_id` on their GKE cluster in order to get the ASM features in the Google Cloud console working (Topology, etc.). Even if it's illustrated in the simple zonal with ASM example, it's not obvious for the ASM module user. We got some evidence internally about Googlers and customers having issues with that.
I'm proposing adding an explicit note about that on the main ASM module doc.
> ASM module - Add a note about the `mesh_id` label on the GKE cluster

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Allows the module to use the `default_auto_upgrade` to infer if the auto_upgrade is enabled for the node pool. This is in line with how the `auto_upgrade` config is [calculated in the `node_pool` resource ](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/compare/master...MrwanBaghdad%3Amaster?body=&expand=1)
```
management {
auto_repair  = lookup(each.value, "auto_repair", true)
auto_upgrade = lookup(each.value, "auto_upgrade", local.default_auto_upgrade)
}
```
> feat: source node pools' auto_upgrade configuration from the GKE default config

- modules/acm/creds.tf
- test/integration/simple_autopilot_public/controls/gcloud.rb
- test/setup/main.tf
Few integration test fixes as CI has been broken
- Autopilot nodes require default SA which is disabled by PF. Support for custom SA is not in the provider yet https://github.com/hashicorp/terraform-provider-google/issues/9505
- ACM sometimes complains the NS was not found. Bumps the sleep by another 30s
- fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1280
> chore: integration test fixes

- .kitchen.yml
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
Update tests to use 1.4 image with TF v1.1.x
> chore: Update tests to use 1.4 image

- autogen/main/cluster.tf.tmpl
- autogen/main/main.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
- modules/beta-public-cluster/versions.tf
Managed Prometheus can now be enabled with the release of the beta provider, `4.25.0`.
Adds an input, `monitoring_enable_managed_prometheus`, to beta cluster submodules using a nested dynamic block in the pre-existing `monitoring_config` block.
The `monitoring_config` block previously only accepted the `monitoring_enabled_components` input, which is now set to null if it is not specified, in order to prevent `SYSTEM_COMPONENTS` from being disabled when `monitoring_enable_managed_prometheus` is set to true.
Fixes PR #1298 
Resolves #1290 and #1167
> Allow enabling managed Prometheus in beta cluster submodules

- .gitignore
- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/versions.tf.tmpl
- cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/versions.tf
- versions.tf
Hi,
with the release `v4.25.0` of the Google provider, we can now use Spot VM on stable cluster.
Thank you
> feat!: promote Spot VM to GA

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
Follow-up #1307
#1307 is missing Autopilot support. This Pull Request will allow Managed Prometheus to be used with Autopilot as well.
> fix: autopilot also supports managed prometheus

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
Follow up to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1307
> Allow enabling managed Prometheus for safer cluster variants

- examples/workload_identity/main.tf
- modules/workload-identity/README.md
* A temporary fix for #1313.  With k8s 1.24 (no channel), the k8s provider resource "kubernetes_service_account" doesn't currently work as expected.  This temporarily sets the workload-identity example/module to k8s 1.23: https://cloud.google.com/kubernetes-engine/docs/release-schedule
> chore: pin workload_identity example to k8s 1.23

- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
exposing use_existing_context variable to allow kubectl wrapper to run kubectl using local kube config context
> Exposing use_existing_context variable

- autogen/main/cluster.tf.tmpl
- autogen/main/main.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/variables.tf
> feat: add `gke_backup_agent_config` arg

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
> feat: promote `max_pods_per_node`, `max_surge`, and `max_unavailable` fields to ga

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/integration/beta_cluster/controls/gcloud.rb
- test/integration/safer_cluster/controls/gcloud.rb
- test/integration/simple_regional/controls/gcloud.rb
`enable_binary_authorization` is now deprecated in favor of the `binary_authorization` block. This preserves the module's interface, but updates the underlying behavior
Fixes #1331
> fix: resolve deprecation warning for binary authorization

- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/safer_cluster/README.md
- examples/safer_cluster/main.tf
- examples/safer_cluster/outputs.tf
- examples/safer_cluster/versions.tf
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/fixtures/safer_cluster/outputs.tf
- test/integration/safer_cluster/controls/gcloud.rb
fixes #1279
Add support for setting `kubernetes_version` when release_channel is set to `UNSPECIFIED`. Per [API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/Shared.Types/Channel) `UNSPECIFIED` is equal to not setting a channel.  Also adds test to validate a custom specified version is used.
> fix: support explicit k8s version with unspecified release channel

- Makefile
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- examples/safer_cluster_iap_bastion/bastion.tf
- test/setup/main.tf
- test/setup/versions.tf
Resolves `Error resolving image name 'debian-cloud/debian-9': Could not find image or family debian-cloud/debian-9`
> chore: follow upstream debian version

- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
Per https://github.com/terraform-google-modules/terraform-google-gcloud/issues/82
> feat: add module_depends_on to workload-identity

- modules/asm/main.tf
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1364
> fix: add depends_on to asm module google_container_cluster data resource

- autogen/main/README.md
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-public-cluster/README.md
Cleaning Up Readme File to fix and remove the redundant reference for  enable_autopilot as functionality is already removed from Terraform code
Fixes Issue #1352
> Cleaning Up readme

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
Enable Cloud DNS support for safer clusters
> feat: cloud dns support for safer clusters

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
> Allow enabling GKE backup agent for safer cluster variants

- modules/acm/README.md
- modules/acm/feature.tf
- modules/acm/variables.tf
> feat: add enable_referential_rules variable

- examples/simple_regional_beta/main.tf
- test/integration/beta_cluster/controls/gcloud.rb
CI seems to be flaking with `Error: googleapi: Error 400: Workload monitoring configuration is not supported for cluster version 1.24.2-gke.1900; a version above 1.20.0 and below 1.24.0 is required., badRequest`. This removes setting `WORKLOADS` component in example.
> chore: remove deprecated workload component to prevent flakes

- examples/private_zonal_with_networking/variables.tf
- examples/simple_regional_with_networking/README.md
- examples/simple_regional_with_networking/variables.tf
No bugs or issue. Just updating acronyms for match with Kubernetes service: scv to svc
> Fix typo on k8s service's acronym to svc

- modules/asm/README.md
- modules/asm/main.tf
- modules/asm/variables.tf
This supports use-cases where the istio-system namespace is already created by existing terraform when adding this module. 
Terraform handles switching from a single resource to one with a `count` seamlessly, so that won't be an issue for anyone upgrading to this version.
> Make creation of istio-system namespace optional

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/versions.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/versions.tf
- test/integration/node_pool/controls/gcloud.rb
- versions.tf
Add support for boot_disk_kms_key for node pools that allows encrypting boot disks with customer-managed encryption keys.
https://cloud.google.com/kubernetes-engine/docs/how-to/using-cmek
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#boot_disk_kms_key
> feat!: add boot_disk_kms_key variable for node pools to GA modules

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-autopilot-public-cluster/versions.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/beta-public-cluster/versions.tf
PR for adding Support fort Cost Allocation in Beta Modules, Issue #1392
> feat!: Adding Support for Cost Allocation Feature in Beta

- examples/simple_windows_node_pool/main.tf
- test/integration/simple_windows_node_pool/controls/gcloud.rb
Windows example tests seem to be flaky. This swaps the example to use containerd variant. 
```
module.this.module.gke.google_container_node_pool.windows_pools["win-pool-01"]: Creating...
Error: error creating NodePool: googleapi: Error 400: Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support., badRequest
```
> chore: fix windows example to use containerd

- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/versions.tf
- versions.tf
Looks like the feature exposed in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1452 was added in 4.36 https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4360-september-12-2022
> fix!: min TPG bump for location_policy

- modules/acm/README.md
- modules/acm/feature.tf
- modules/acm/variables.tf
Add support for https_proxy parameter for the config_sync.git block
> Add support for https_proxy parameter for the config_sync.git block

- test/integration/beta_cluster/controls/gcloud.rb
- test/integration/sandbox_enabled/controls/gcloud.rb
- test/integration/simple_autopilot_public/controls/gcloud.rb
- test/integration/simple_regional/controls/gcloud.rb
- test/integration/simple_regional_with_kubeconfig/controls/gcloud.rb
- test/integration/simple_regional_with_networking/controls/gcloud.rb
- test/integration/simple_zonal/controls/gcloud.rb
API return for https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#privateclusterconfig seems to have changed. Updated `uses public nodes and master endpoint` to explicitly validate  `enablePrivateEndpoint` and `enablePrivateNodes` are not set.
> chore: test fixes

- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
This was recently added to the cluster modules, so forwarding the value from safer_cluster as well.
> feat: Allow enabling cost management for safer_cluster module

- .github/CODEOWNERS
> chore: Delete Stale CODEOWNERS

- examples/simple_autopilot_private/outputs.tf
`ca_certificate` output variable in simple autopilot example needs marking as sensitive
> chore: annotate sensitive output variable

- autogen/main/cluster.tf.tmpl
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/cluster.tf
This PR fixes service_account support for the Autopilot modules. Previously, the supplied was ignored contrary to documentation.
> fix: support custom service account for autopilot

- autogen/main/cluster.tf.tmpl
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/cluster.tf
You cannot set datapath for Autopilot clusters.
Fixes #1446
> fix: remove datapath provider from Autopilot modules

- autogen/main/main.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
This PR fixes the issue described in #1542: the legacy `EXPOSE` value for `node_metadata` should be mapped to the new `GCE_METADATA` value instead of the opposite, and `GCE_METADATA` should be left as is.
> fix: node_metadata mapping for GCE_METADATA (#1542)

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
Changes introduced in [feat: add nodepool autoscaling vars avail in GKE 1.24.1 ](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1415) result in conflicts when using total limits.
Currently, [google_container_node_pool](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool) resource states that total and per zone limits can't be used together.
To address this issue and maintain the current behaviour where min and max values for a node pool are set by default, this fix strays from standard behaviour where the value is set to null. Please advise if this is acceptable.
If this is not, I have prepared a second fix where the values are nulled. [fix: nodepool autoscaling vars avail in GKE 1.24.1 result in …
> fix: nodepool autoscaling vars avail in GKE 1.24.1 result in conflicts. Preserve default behavior

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- examples/simple_autopilot_private/main.tf
- examples/simple_autopilot_public/main.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- test/integration/simple_autopilot_private/simple_autopilot_private_test.go
- test/integration/simple_autopilot_public/simple_autopiliot_public_test.go
* dynamically configure `node_pool_auto_config` block with `network_tags` nested block
* Addressing https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1496
> feat: allow setting network tags on autopilot clusters

- modules/acm/creds.tf
When using both config sync and policy controller the existing binding resources conflicts with each other and causes a constant diff.
This PR will cause a diff in existing configurations, but when applying it should actually apply the the binding to both members resulting in the intended outcome and no further diffs.
> fix(acm)!: prevent conflicts in IAM binding

- examples/workload_identity/main.tf
- modules/workload-identity/README.md
- modules/workload-identity/versions.tf
The issue with hashicorp/kubernetes hanging creating service accounts was resolved in https://github.com/hashicorp/terraform-provider-kubernetes/pull/1792 in https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.13.0
This reverts the temporary limitation of the workload identity module to 1.23 added in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1315 to resolve https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1313, and updates the minimum required version of hashicorp/kubernetes to 2.13.0 for the workload-identity module
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1582
cc @bharathkkb @apeabody
> Fix: Remove 1.23 restriction on workload identity module

- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
This PR adds the ability to set the enable_private_notes option in network_config for a pool of public cluster nodes.
We already had a cluster in which the nodes had public addresses. We wanted to change this property of the node without recreating the cluster. We would have to recreate the cluster, since the private_cluster_config property is immutable and we cannot use the module for a private cluster.
> feat: add enable_private_nodes options to node_pool network_config

- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
- modules/beta-private-cluster-update-variant/versions.tf
- modules/beta-private-cluster/versions.tf
- modules/beta-public-cluster-update-variant/versions.tf
- modules/beta-public-cluster/versions.tf
- modules/private-cluster-update-variant/versions.tf
- modules/private-cluster/versions.tf
- versions.tf
https://github.com/hashicorp/terraform-provider-google/issues/14602#issuecomment-1549689089
> fix: avoid TPG 4.65.0 and 4.65.1

- modules/acm/creds.tf
- modules/acm/policy_bundles.tf
The module name is used by the gcloud module in paths, so long uls or special characters could cause issues depending on the local filesystem.
> fix: policy bundles now use idx as resource name (bundles will be re-applied)

- examples/simple_zonal_with_acm/acm.tf
- modules/acm/policy_bundles.tf
revert the `idx` portion of https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1657
> fix: update policy-essentials hash 59f4695 using ref

- autogen/main/firewall.tf.tmpl
- firewall.tf
- modules/beta-autopilot-private-cluster/firewall.tf
- modules/beta-autopilot-public-cluster/firewall.tf
- modules/beta-private-cluster-update-variant/firewall.tf
- modules/beta-private-cluster/firewall.tf
- modules/beta-public-cluster-update-variant/firewall.tf
- modules/beta-public-cluster/firewall.tf
- modules/private-cluster-update-variant/firewall.tf
- modules/private-cluster/firewall.tf
- test/integration/safer_cluster/safer_cluster_test.go
This, to be able to have longer and unique names.
The firewall API supports 63 charters
Solves #1527
https://cloud.google.com/compute/docs/reference/rest/v1/firewalls
```shell
echo gke--intra-cluster-egress |wc -c
26
expr 63 - 26
37
```
> fix: set max firewall name to 36

- test/setup/main.tf
* use `random_string` for a larger collusion domain https://github.com/terraform-google-modules/terraform-google-project-factory/pull/735
> chore: uses random_string for test setup

- modules/acm/README.md
- modules/acm/feature.tf
- modules/acm/variables.tf
This PR exposes the `gcp_service_account_email` configuration setting. Without this, users cannot configure a Service Account to access the ACM Git repository.
> feat: support configuring ACM git service account email

- modules/fleet-membership/README.md
- modules/fleet-membership/outputs.tf
> feat: add project and location output to fleet-membership

- test/fixtures/simple_regional/example.tf
- test/fixtures/simple_regional/network.tf
- test/integration/simple_regional/testdata/TestSimpleRegional.json
Tests seem to be failing with `Error: googleapi: Error 403: You cannot create more than 3 clusters in location us-central1; to create more than 3, you must request an increase of your Google Compute Engine quota for region us-central1 to 25 CPUs or more.`
> chore: update test regions

- modules/acm/creds.tf
Currently enabling only one of `enable_config_sync` or `enable_policy_controller` will cause a string template containing `null`. See:
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/acm/creds.tf#L47
This removes the null item and creates instead an array of 0 to 2 elements.
> fix(acm): Allow to enable config_sync or policy_controller standalone

- autogen/main/variables.tf.tmpl
- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
Enable vulnerability and audit modes for workloads.
> feat!: enabling vulnerability and audit modes for workloads

- test/integration/beta_cluster/testdata/TestBetaCluster.json
- test/integration/simple_regional/testdata/TestSimpleRegional.json
```
Error:      	Not equal: 
expected: "{\n    \"advancedDatapathObservabilityConfig\": {\n      \"relayMode\": \"DISABLED\"\n    },\n    \"componentConfig\": {\n      \"enableComponents\": [\n        \"SYSTEM_COMPONENTS\"\n      ]\n    },\n    \"managedPrometheusConfig\": {}\n  }"
actual  : "{\n    \"advancedDatapathObservabilityConfig\": {\n      \"enableRelay\": false\n    },\n    \"componentConfig\": {\n      \"enableComponents\": [\n        \"SYSTEM_COMPONENTS\"\n      ]\n    },\n    \"managedPrometheusConfig\": {}\n  }"
Diff:
--- Expected
+++ Actual
@@ -2,3 +2,3 @@
"advancedDatapathObservabilityConfig": {
-      "relayMode": "DISABLED"
+      "enableRelay": false
},
Test:       	TestBetaCluster
Messages:   	expected monitoringConfig to match fixture { …
```
> chore: update advancedDatapathObservabilityConfig in CI

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Trying to support the ticket id https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1802. The ticket required to have pod_range to deploy node_pools to a different range from the cluster.
Adding extra support for placement group as well. These features are available in private-cluster-beta and now supported in GA
> feat: add support for pod_range in private cluster

- modules/asm/hub.tf
That resource was added recently in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1702
Bit I get this error when I try to apply it with my config:
```hcl
module "asm" {
source = "git@github.com:terraform-google-modules/terraform-google-kubernetes-engine.git//modules/asm?ref=3c9a634ceef3fe8fc073de161f17f0064f424c04"
project_id                = var.project_id
cluster_name              = module.gke.name
cluster_location          = module.gke.location
mesh_management           = "MANAGEMENT_AUTOMATIC"
multicluster_mode         = "connected"
enable_cni                = true
enable_fleet_registration = true
enable_mesh_feature       = true
}
```
```
$ terraform plan
<...>
╷
│ Error: 1 error occurred:
│ 	* Failed to retrieve project, pid: , err: project: …
```
> fix: Add project ID to the fleet feature membership for ASM

- autogen/main/sa.tf.tmpl
- docs/upgrading_to_v30.0.md
- modules/beta-autopilot-private-cluster/sa.tf
- modules/beta-autopilot-public-cluster/sa.tf
- modules/beta-private-cluster-update-variant/sa.tf
- modules/beta-private-cluster/sa.tf
- modules/beta-public-cluster-update-variant/sa.tf
- modules/beta-public-cluster/sa.tf
- modules/private-cluster-update-variant/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
This update follows changes from #1757 and reverts #1827.
The role `roles/container.nodeServiceAccount` is deprecated now and it is replaced with new `roles/container.defaultNodeServiceAccount` role. Unfortunately this is not yet documented in Google docs.
As the scope of the new role is smaller than the old one, this should be considered breaking change.
> feat!: Update least privilege default service account

- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
Straightforward change to allow passing `display_name` and `description` to the Service Account created by workload identity (as input variables `gcp_sa_display_name` and `gcp_sa_description`).
If these are not given (they default to null), the behaviour is the same as before.
Use case: we want to implement some conventions around service account display_name and description for all service accounts to follow (e.g. document how they were created). Without this change, this is only possible by moving the google service account terraform resource outside of the workload-identity module, which is cumbersome state juggling for existing service accounts.
I am not exactly sure what kind of tests are needed here, please advise.
> feat: workload-identity: Allow passing Google Service Account display_name and description 

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Fixes https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1671
Relates to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1061
According to the documentation, `mesh_id` label is supposed to be set explicitly on the GKE cluster:
- [asm module doc] https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/d82c50c9cd059fd581f7ab5fe943dfada3cce0c3/modules/asm/README.md#L36-L43
- [Google doc for managed ASM] https://cloud.google.com/service-mesh/docs/managed/provision-managed-anthos-service-mesh#configure_your_fleet
- [Google doc for in-cluster ASM] https://cloud.google.com/service-mesh/docs/unified-install/project-cluster-setup#set_up_your_cluster
However, right now this label is ignored by …
> fix: Do not ignore "mesh_id" label on "google_container_cluster" resource

- autogen/main/variables.tf.tmpl
- examples/simple_autopilot_private/main.tf
- examples/simple_autopilot_private_non_default_sa/main.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
Fixing a bug with Autopilot Private cluster submodule
The default value provided in the module makes it not possible to create multiple clusters in the same VPC. This was likely added to cover for a provider bug that required `master_ipv4_cidr_block` to be set even for autopilot clusters but it was fixed days after the module additions for autopilot private were merged.
* [Docs](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#req_res_lim) :
```
Note: In an Autopilot cluster, the --master-ipv4-cidr parameter is assigned a 
subnet within the 172.16.0.0/16 range by default. 
This range allows for various subnet sizes.
```
* [Provider docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster):
```
master_ipv4_cidr_block …
```
> fix: make master_ipv4_cidr_block optional for autopilot

- README.md
- autogen/main/variables.tf.tmpl
- autogen/safer-cluster/main.tf.tmpl
- autogen/safer-cluster/variables.tf.tmpl
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
- modules/safer-cluster-update-variant/README.md
- modules/safer-cluster-update-variant/main.tf
- modules/safer-cluster-update-variant/variables.tf
- modules/safer-cluster/README.md
- modules/safer-cluster/main.tf
- modules/safer-cluster/variables.tf
- variables.tf
This adds the possibility to configure what monitoring components should be enabled for the safer cluster variants.
> feat(safer-clusters): add components selection for monitoring

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
> feat: network tags for autoprovisioned node pools

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
While still list in the documentation as Beta (https://github.com/GoogleCloudPlatform/magic-modules/pull/10408), `enable_l4_ilb_subsetting` was promoted to GA in TPG v4.44.0
Fixes: #1863
> feat: add enable_l4_ilb_subsetting for GA TPG

- README.md
- autogen/main/README.md
- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
PR adds secondary_boot_disks setting to cluster.tf in the node_config part.
> feat: Add secondary_boot_disks to node_pool configuration.

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Fixes changes implemented in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1944
During renaming of variable I forgot to change second variable name in dynamic block. This PR fixes it.
cc @apeabody
> fix: dynamic block ephemeral_storage_local_ssd_config

- autogen/main/main.tf.tmpl
- autogen/main/outputs.tf.tmpl
- modules/beta-autopilot-private-cluster/main.tf
- modules/beta-autopilot-private-cluster/outputs.tf
- modules/beta-autopilot-public-cluster/main.tf
- modules/beta-autopilot-public-cluster/outputs.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/main.tf
- modules/beta-private-cluster/outputs.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster-update-variant/outputs.tf
- modules/beta-public-cluster/main.tf
- modules/beta-public-cluster/outputs.tf
It should return the value of "Identity Service" feature flag (`local.cluster_identity_service_enabled`), not "Pod Security Policy"(`local.cluster_pod_security_policy_enabled`)
It seems that there was a typo in the initial implementation of this feature in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1142.
Note: the local variable `local.cluster_output_identity_service_enabled ` was already defined earlier, but it was deleted in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1598 because it wasn't used.
> fix: Fix the value of output "identity_service_enabled" in beta modules

- autogen/main/sa.tf.tmpl
- modules/beta-autopilot-private-cluster/sa.tf
- modules/beta-autopilot-public-cluster/sa.tf
- modules/beta-private-cluster-update-variant/sa.tf
- modules/beta-private-cluster/sa.tf
- modules/beta-public-cluster-update-variant/sa.tf
- modules/beta-public-cluster/sa.tf
- modules/private-cluster-update-variant/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
The `random_string` resource is only used to create the default service account name. It is not needed when not creating a service account or when using a custom service account name.
Fixes #1808
Fixes #1690
> fix: skip service account `random_string` when not needed

- examples/simple_fleet_app_operator_permissions/main.tf
- modules/fleet-app-operator-permissions/README.md
- modules/fleet-app-operator-permissions/variables.tf
Enable `groups` and `users` parameters to be optional.
> fix(fleet_app_operator_permissions): optional groups and users

- modules/fleet-app-operator-permissions/main.tf
Fixes: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/2046
Switch from `google_project_iam_binding` which is authoritative for the role, to `google_project_iam_member`
> fix(fleet_app_operator_permissions): enable multi use per project

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
This currently plumbs `enable_gcfs` with a default of `null`, however in a future breaking change it will be `true`.
> fix(autopilot): option to configure gcfs

- autogen/main/variables.tf.tmpl
- docs/upgrading_to_v33.0.md
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
Enable private_nodes by default on private_cluster
> feat(private_cluster)!: enable private nodes by default

- autogen/main/versions.tf.tmpl
- modules/beta-autopilot-private-cluster/versions.tf
- modules/beta-autopilot-public-cluster/versions.tf
Workaround: https://github.com/hashicorp/terraform-provider-google/issues/19428
> fix: avoid TPG v6.2.0 with Autopilot

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/integration/private_zonal_with_networking/testdata/TestPrivateZonalWithNetworking.json
Even with 6.4.0 or 5.44.1 (with my upstream fix), I am still seeing the issue described in #2100, since the earlier fixes were related to the default node-pool vs explicitly defined ones.
Fixes #2100
This basically replicates the fixes from #2093, #2095, but at the scope of implicitly defined nodepools.
> fix: allow null `enable_gcfs` setting in defined nodepools

- examples/simple_regional_with_ipv6/main.tf
This resolves a warning that comes up when running the lint checks locally, and seems to bring it in line with other examples
The other thing I noticed when running the lint script locally from a fork is that it actually locally updates the module source when it's defined like this (e.g., `examples/simple_fleet_app_operator_permissions/main.tf`, and one other):
```hcl
module "permissions" {
source = "../../modules/fleet-app-operator-permissions"
```
it will get updated to this somewhere in the process -- not sure where, but maybe that's also something that should be fixed?
```diff
--- a/examples/autopilot_private_firewalls/main.tf
+++ b/examples/autopilot_private_firewalls/main.tf
@@ -33,7 +33,7 @@ provider "kubernetes" {
}
module "gke" {
-  source                            = …
```
> chore: pin version in `simple_regional_with_ipv6` example

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Resolve `terraform_deprecated_lookup` warning for `lookup()` calls with only 2 arguments (no default).
See:
https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/rules/terraform_deprecated_lookup.md
> refactor: replace non-default `lookup()` calls with direct access

- .kitchen.yml
With the test kitchen version (3.5) used by the tests, there are some parameters which have moved to new locations.
Follow the suggestions of `kitchen doctor`.
> chore: update kitchen config

- examples/autopilot_private_firewalls/main.tf
- examples/simple_fleet_app_operator_permissions/main.tf
- Update module source. This should prevent the source from getting rewritten when tests are run locally
- Add missing version spec to match other modules
Follow-up to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2115#issuecomment-2375056239
For example this:
```hcl
module "permissions" {
source = "../../modules/fleet-app-operator-permissions"
}
```
gets rewritten like this when the docker test / lint make target is run.
```diff
--- a/examples/autopilot_private_firewalls/main.tf
+++ b/examples/autopilot_private_firewalls/main.tf
@@ -33,7 +33,7 @@ provider "kubernetes" {
}
module "gke" {
-  source                            = "../../modules/beta-autopilot-private-cluster/"
+  source                            = …
```
> chore: update example module sources and versions

- .gitignore
If there's a template repo, maybe this should get added there as well?
> chore: ignore top level `.terraform.lock`

- autogen/main/cluster.tf.tmpl
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
Set `master_ipv4_cidr_block` to `null` when `private_endpoint_subnetwork` is set, as the two conflict with an API level error being thrown:
`Error: googleapi: Error 400: When masterIpv4Cidr is set, privateEndpointSubnetwork must be unset.`
Fixes #2119
This would have the effect of silently ignoring the setting even when `master_ipv4_cidr_block` is explicitly set. A better fix might be to throw an error, but given that there's a baked in default and that terraform module validation can't look at the values of other variables, I don't think that would be trivial.
> fix: ignore control plane network when private endpoint subnet is set

- modules/acm/feature.tf
- use the actual membership location rather than always global
> fix(acm): use membership registration location

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
_**Motivation**_
The current set of confidential node support is available only at the cluster level, but the confidential node support at the node level is required to have new node pools created with confidential nodes.
_**Summary of changes**_
Added `enable_confidential_nodes` variable at the node pool level.
**_P.S_**: This is addressing the issue https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1386 and has same changes as that of the PR https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1756. As the PR author has not responded for the review comments, I'm thus creating a fresh PR as this feature is needed at the earliest.
Fixes: #1386
Closes: #1756
> feat: added confidential-nodes flag for node-pools

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/cluster.tf
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/cluster.tf
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
Make `enable_identity_service` optional, and handle the case where the value changes by only suppressing the dynamic block if `var.enable_identity_service` is null vs. false.
Fixes #2129
> fix: allow changing `enable_identity_service` value in place

- autogen/main/cluster.tf.tmpl
- build/int.cloudbuild.yaml
- cluster.tf
- examples/simple_regional_cluster_autoscaling/README.md
- examples/simple_regional_cluster_autoscaling/main.tf
- examples/simple_regional_cluster_autoscaling/outputs.tf
- examples/simple_regional_cluster_autoscaling/test_outputs.tf
- examples/simple_regional_cluster_autoscaling/variables.tf
- examples/simple_regional_cluster_autoscaling/versions.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/fixtures/simple_regional_cluster_autoscaling/example.tf
- test/fixtures/simple_regional_cluster_autoscaling/network.tf
- test/fixtures/simple_regional_cluster_autoscaling/outputs.tf
- test/fixtures/simple_regional_cluster_autoscaling/variables.tf
- test/integration/simple_regional_cluster_autoscaling/simple_regional_cluster_autoscaling_test.go
- test/integration/simple_regional_cluster_autoscaling/testdata/TestSimpleRegionalClusterAutoscaling.json
While #1817 added autopilot support for adding tags to `node_pool_auto_config` when `add_cluster_firewall_rules` is set to `true`, the same change did not apply for standard (non-autopilot) clusters with cluster level autoscaling (nodepool autoprovisioning) in place,
Fixes #2104
> fix: add target tags to `node_pool_auto_config` for standard clusters

- test/integration/private_zonal_with_networking/testdata/TestPrivateZonalWithNetworking.json
> chore(CI): update testdata with insecureKubeletReadonlyPortEnabled

- autogen/main/cluster.tf.tmpl
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
Code in this PR forces re-creation of node pools with changes in `secondary_boot_disk` and `local_ssd_ephemeral_count` (for beta variants). Because of these are currently not in `random_id.name` keepers, the random suffix (and the entire node pool name) remains the same on updating these variables and replacing node pool resource results in `resource - <node_pool_path> - already exists` error.
Both of these parameters require node pool re-creation as per TF spec:
* `secondary_boot_disk`: [secondary_boot_disks](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/container/node_config.go#L287)
* `local_ssd_ephemeral_count`: [ephemeral_storage_local_ssd_config](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/container/node_config.g …
> fix(node_pools): Update Variants: Add recreate for `secondary_boot_disk` and `local_ssd_ephemeral_count` (beta)

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
The field name confidential_node in dynamic block confidential_nodes at nodepool level is incorrect, it should be enabled_confidential_nodes  
dynamic "confidential_nodes" {
for_each = lookup(each.value, "enable_confidential_nodes", null) != null ? [each.value.confidential_nodes] : []
content {
enabled = confidential_nodes.value
}
> Fix: correct confidential node field name

- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/node_pool/main.tf
- examples/node_pool_update_variant/main.tf
- examples/private_zonal_with_networking/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/integration/private_zonal_with_networking/testdata/TestPrivateZonalWithNetworking.json
Add `insecureKubeletReadonlyPortEnabled` to `node_config.kubelet_config` for the default node-pool and for additional pools. It may also be necessary to define the top level `node_config` more broadly for the case where `remove_default_node_pool` is set to false, which should probably be handled separately.
Also, the upstream provider (intentionally) uses an enum of `"TRUE"` / `"FALSE"` vs. a boolean. Update the code to follow this, and add a test case (also suggested by @apeabody) that covers the cluster level setting vs node pool one.
Fixes #2013
> fix: send provider enum values for `insecureKubeletReadonlyPortEnabled`

- modules/workload-identity/README.md
- modules/workload-identity/main.tf
- modules/workload-identity/variables.tf
Adds [create_ignore_already_exists](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account#create_ignore_already_exists) to workload-identity module to ignore an already existing google-service-account when hitting the [Provider produced inconsistent result after apply](https://github.com/hashicorp/terraform-provider-google/issues/18087) issue.
Fixes #2141
> feat: Add create_ignore_already_exists to workload_identity

- modules/workload-identity/versions.tf
#2142 introduced `gcp_sa_create_ignore_already_exists` variable for workload-identity module without bumping to TPG<=5.12.0 and fails on installations with older TPG.
> fix(TPG>=5.12.0): Bump for #2142 (#2141)

- README.md
- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- cluster.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/cluster.tf
- modules/private-cluster/variables.tf
- variables.tf
promote `enable_gcfs` to GA in main module
> feat(TPG>=6.5.0)!: promote `enable_gcfs` to GA

- autogen/main/main.tf.tmpl
- main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/beta-public-cluster-update-variant/main.tf
- modules/beta-public-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
terraform's `toset` seems to strip falsy values from maps (at least, that's what we're seeing with terraform 1.9.8), so setting `auto_repair` to `false` is not passed through and ends up taking the default `true` value.
Use a for expression instead, it's simpler and works too
> fix: node pool options cannot be set to false

- autogen/main/main.tf.tmpl
- docs/upgrading_to_v35.0.md
- modules/beta-autopilot-private-cluster/main.tf
- modules/beta-private-cluster-update-variant/main.tf
- modules/beta-private-cluster/main.tf
- modules/private-cluster-update-variant/main.tf
- modules/private-cluster/main.tf
We should use the `private_endpoint` when `enable_private_endpoint` is true, even if `deploy_using_private_endpoint` is not.
Needed for TPG v6.11+
> fix(private-cluster)!: use private endpoint

- autogen/main/outputs.tf.tmpl
- modules/beta-autopilot-private-cluster/outputs.tf
- modules/beta-private-cluster-update-variant/outputs.tf
- modules/beta-private-cluster/outputs.tf
- modules/private-cluster-update-variant/outputs.tf
- modules/private-cluster/outputs.tf
- test/integration/simple_regional_with_gateway_api/testdata/TestSimpleRegionalWithGatewayAPI.json
> fix(private-cluster): master_ipv4_cidr_block on enable_private_nodes

- autogen/main/cluster.tf.tmpl
- autogen/main/variables.tf.tmpl
- examples/simple_autopilot_private/main.tf
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/cluster.tf
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/cluster.tf
- modules/beta-autopilot-public-cluster/variables.tf
- test/integration/simple_regional_with_gateway_api/testdata/TestSimpleRegionalWithGatewayAPI.json
- test/integration/testutils/utils.go
> feat(autopilot): add insecure_kubelet_readonly_port_enabled

- autogen/main/sa.tf.tmpl
- modules/beta-autopilot-private-cluster/sa.tf
- modules/beta-autopilot-public-cluster/sa.tf
- modules/beta-private-cluster-update-variant/sa.tf
- modules/beta-private-cluster/sa.tf
- modules/beta-public-cluster-update-variant/sa.tf
- modules/beta-public-cluster/sa.tf
- modules/private-cluster-update-variant/sa.tf
- modules/private-cluster/sa.tf
- sa.tf
- When creating cluster SA enable [`roles/serviceusage.serviceUsageConsumer`](https://cloud.google.com/kubernetes-engine/docs/how-to/image-streaming#requirements) if standard cluster with enable_gcfs, or autopilot cluster
Fixes: #2251
> feat: add serviceUsageConsumer to SA for GCFS

- build/int.cloudbuild.yaml
With [blueprint-test v0.17.5](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/releases/tag/infra%2Fblueprint-test%2Fv0.17.5) we can move to a smaller runner
> chore(CI): E2_STANDARD_2 machine type

- README.md
- autogen/main/variables.tf.tmpl
- modules/beta-autopilot-private-cluster/README.md
- modules/beta-autopilot-private-cluster/variables.tf
- modules/beta-autopilot-public-cluster/README.md
- modules/beta-autopilot-public-cluster/variables.tf
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/variables.tf
- variables.tf
The newly introduced flag for `enterprise_config` (added in #2298) can only take in the values `STANDARD` or `ENTERPRISE` as by the Google API. The mentioned value of `DEFAULT` isn't valid
- Corrected values from `DEFAULT` to `STANDARD`
- Added validation for the variables
> fix: Update files with correct values for enterprise config

- autogen/main/cluster.tf.tmpl
- cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
The `boot_disk_kms_key` field was (accidentally?) **beta cluster** gated in the `default-pool`.
Fixes: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/2344
> fix: remove default-pool beta gate for boot_disk_kms_key

- README.md
- autogen/main/variables.tf.tmpl
- metadata.yaml
- modules/beta-private-cluster-update-variant/README.md
- modules/beta-private-cluster-update-variant/metadata.yaml
- modules/beta-private-cluster-update-variant/variables.tf
- modules/beta-private-cluster/README.md
- modules/beta-private-cluster/metadata.yaml
- modules/beta-private-cluster/variables.tf
- modules/beta-public-cluster-update-variant/README.md
- modules/beta-public-cluster-update-variant/metadata.yaml
- modules/beta-public-cluster-update-variant/variables.tf
- modules/beta-public-cluster/README.md
- modules/beta-public-cluster/metadata.yaml
- modules/beta-public-cluster/variables.tf
- modules/private-cluster-update-variant/README.md
- modules/private-cluster-update-variant/metadata.yaml
- modules/private-cluster-update-variant/variables.tf
- modules/private-cluster/README.md
- modules/private-cluster/metadata.yaml
- modules/private-cluster/variables.tf
- variables.tf
[Starting on July 1, 2025, **new** Google Cloud organizations that you create won't support Identity Service for GKE.](https://cloud.google.com/kubernetes-engine/docs/how-to/oidc#external-idp-authentication-methods) The recommendation is to use [Workforce Identity Federation](https://cloud.google.com/iam/docs/workforce-identity-federation).
Fixes: #2413
> fix: note org support of Identity Service for GKE

- autogen/main/cluster.tf.tmpl
- cluster.tf
- examples/node_pool/main.tf
- modules/beta-private-cluster-update-variant/cluster.tf
- modules/beta-private-cluster/cluster.tf
- modules/beta-public-cluster-update-variant/cluster.tf
- modules/beta-public-cluster/cluster.tf
- modules/private-cluster-update-variant/cluster.tf
- modules/private-cluster/cluster.tf
- test/integration/node_pool/testdata/TestNodePool.json
Closes #2321
Add the nodepool cgroup mode to the NAP config
> fix: Add the nodepool cgroup mode to the NAP config
